// SPDX-License-Identifier: AGPL-3.0
// AUTO-GENERATED by processing/generateSolidity.py. Do not edit by hand.
pragma solidity ^0.8.0;

import {Script} from "forge-std/Script.sol";
import {DeployData} from "../DeployData.sol";
import {Type} from "../../src/Enums.sol";
import {MonStats} from "../../src/Structs.sol";
import {GachaTeamRegistry} from "../../src/game-layer/GachaTeamRegistry.sol";
import {IEffect} from "../../src/effects/IEffect.sol";
import {Overclock} from "../../src/effects/battlefield/Overclock.sol";
import {DualShock} from "../../src/mons/volthare/DualShock.sol";
import {MegaStarBlast} from "../../src/mons/volthare/MegaStarBlast.sol";
import {PreemptiveShock} from "../../src/mons/volthare/PreemptiveShock.sol";
import {Quickstorm} from "../../src/mons/volthare/Quickstorm.sol";
import {RoundTrip} from "../../src/mons/volthare/RoundTrip.sol";
import {ITypeCalculator} from "../../src/types/ITypeCalculator.sol";

abstract contract VolthareDeploy is Script {
    function deployVolthare(GachaTeamRegistry registry) internal returns (DeployData[] memory) {
        DeployData[] memory deployedContracts = new DeployData[](5);

        // Cache commonly used addresses
        address typecalculator = vm.envAddress("TYPE_CALCULATOR");
        address zapstatus = vm.envAddress("ZAP_STATUS");

        address[5] memory addrs;

        {
            addrs[0] = address(new RoundTrip(ITypeCalculator(typecalculator)));
            deployedContracts[0] = DeployData({name: "Round Trip", contractAddress: addrs[0]});
        }
        {
            addrs[1] = address(new MegaStarBlast(ITypeCalculator(typecalculator), IEffect(zapstatus), IEffect(vm.envAddress("OVERCLOCK"))));
            deployedContracts[1] = DeployData({name: "Mega Star Blast", contractAddress: addrs[1]});
        }
        {
            addrs[2] = address(new DualShock(ITypeCalculator(typecalculator), IEffect(zapstatus), Overclock(vm.envAddress("OVERCLOCK"))));
            deployedContracts[2] = DeployData({name: "Dual Shock", contractAddress: addrs[2]});
        }
        {
            addrs[3] = address(new Quickstorm(ITypeCalculator(typecalculator), IEffect(zapstatus)));
            deployedContracts[3] = DeployData({name: "Quickstorm", contractAddress: addrs[3]});
        }
        {
            addrs[4] = address(new PreemptiveShock(ITypeCalculator(typecalculator)));
            deployedContracts[4] = DeployData({name: "Preemptive Shock", contractAddress: addrs[4]});
        }

        _registerVolthare(registry, addrs);

        return deployedContracts;
    }

    function _registerVolthare(GachaTeamRegistry registry, address[5] memory addrs) internal {
        MonStats memory stats = MonStats({
            hp: 310,
            stamina: 5,
            speed: 311,
            attack: 120,
            defense: 184,
            specialAttack: 255,
            specialDefense: 176,
            type1: Type.Lightning,
            type2: Type.Cyber
        });
        uint256[] memory moves = new uint256[](5);
        moves[0] = 0x5a4820a000000000000000000000000000000000000000000000000000000000 | uint256(uint160(vm.envAddress("ZAP_STATUS")));
        moves[1] = 0x0030100000000000000000010000000000000000000000000000000000000000 | uint256(uint160(addrs[0]));
        moves[2] = 0x0050300000000000000000010000000000000000000000000000000000000000 | uint256(uint160(addrs[1]));
        moves[3] = 0x0030000000000000000000010000000000000000000000000000000000000000 | uint256(uint160(addrs[2]));
        moves[4] = 0x0030200000000000000000010000000000000000000000000000000000000000 | uint256(uint160(addrs[3]));
        uint256[] memory abilities = new uint256[](1);
        abilities[0] = uint256(uint160(addrs[4]));
        bytes32[] memory keys = new bytes32[](0);
        bytes32[] memory values = new bytes32[](0);
        registry.createMon(8, stats, moves, abilities, keys, values);
    }
}

contract SetupVolthare is VolthareDeploy {
    function run() external returns (DeployData[] memory deployedContracts) {
        vm.startBroadcast();
        deployedContracts = deployVolthare(GachaTeamRegistry(vm.envAddress("GACHA_TEAM_REGISTRY")));
        vm.stopBroadcast();
    }
}
