// SPDX-License-Identifier: AGPL-3.0
// AUTO-GENERATED by processing/generateSolidity.py. Do not edit by hand.
pragma solidity ^0.8.0;

import {Script} from "forge-std/Script.sol";
import {DeployData} from "../DeployData.sol";
import {Type} from "../../src/Enums.sol";
import {MonStats} from "../../src/Structs.sol";
import {GachaTeamRegistry} from "../../src/game-layer/GachaTeamRegistry.sol";
import {Angery} from "../../src/mons/gorillax/Angery.sol";
import {RockPull} from "../../src/mons/gorillax/RockPull.sol";
import {ITypeCalculator} from "../../src/types/ITypeCalculator.sol";

abstract contract GorillaxDeploy is Script {
    function deployGorillax(GachaTeamRegistry registry) internal returns (DeployData[] memory) {
        DeployData[] memory deployedContracts = new DeployData[](2);

        address[2] memory addrs;

        {
            addrs[0] = address(new RockPull(ITypeCalculator(vm.envAddress("TYPE_CALCULATOR"))));
            deployedContracts[0] = DeployData({name: "Rock Pull", contractAddress: addrs[0]});
        }
        {
            addrs[1] = address(new Angery());
            deployedContracts[1] = DeployData({name: "Angery", contractAddress: addrs[1]});
        }

        _registerGorillax(registry, addrs);

        return deployedContracts;
    }

    function _registerGorillax(GachaTeamRegistry registry, address[2] memory addrs) internal {
        MonStats memory stats = MonStats({
            hp: 407,
            stamina: 5,
            speed: 129,
            attack: 302,
            defense: 175,
            specialAttack: 112,
            specialDefense: 176,
            type1: Type.Earth,
            type2: Type.None
        });
        uint256[] memory moves = new uint256[](4);
        moves[0] = 0x00f0300000000000000000010000000000000000000000000000000000000000 | uint256(uint160(addrs[0]));
        moves[1] = 0x5f02300000000000000000000000000000000000000000000000000000000000;
        moves[2] = 0x460a200000000000000000000000000000000000000000000000000000000000;
        moves[3] = 0x2802100000000000000000000000000000000000000000000000000000000000;
        uint256[] memory abilities = new uint256[](1);
        abilities[0] = (uint256(1) << 248) | uint256(uint160(addrs[1]));
        bytes32[] memory keys = new bytes32[](0);
        bytes32[] memory values = new bytes32[](0);
        registry.createMon(4, stats, moves, abilities, keys, values);
    }
}

contract SetupGorillax is GorillaxDeploy {
    function run() external returns (DeployData[] memory deployedContracts) {
        vm.startBroadcast();
        deployedContracts = deployGorillax(GachaTeamRegistry(vm.envAddress("GACHA_TEAM_REGISTRY")));
        vm.stopBroadcast();
    }
}
