// SPDX-License-Identifier: AGPL-3.0
// AUTO-GENERATED by processing/generateSolidity.py. Do not edit by hand.
pragma solidity ^0.8.0;

import {Script} from "forge-std/Script.sol";
import {DeployData} from "../DeployData.sol";
import {Type} from "../../src/Enums.sol";
import {MonStats} from "../../src/Structs.sol";
import {GachaTeamRegistry} from "../../src/game-layer/GachaTeamRegistry.sol";
import {CarrotHarvest} from "../../src/mons/sofabbi/CarrotHarvest.sol";
import {Gachachacha} from "../../src/mons/sofabbi/Gachachacha.sol";
import {GuestFeature} from "../../src/mons/sofabbi/GuestFeature.sol";
import {SnackBreak} from "../../src/mons/sofabbi/SnackBreak.sol";
import {ITypeCalculator} from "../../src/types/ITypeCalculator.sol";

abstract contract SofabbiDeploy is Script {
    function deploySofabbi(GachaTeamRegistry registry) internal returns (DeployData[] memory) {
        DeployData[] memory deployedContracts = new DeployData[](4);

        // Cache commonly used addresses
        address typecalculator = vm.envAddress("TYPE_CALCULATOR");

        address[4] memory addrs;

        {
            addrs[0] = address(new Gachachacha(ITypeCalculator(typecalculator)));
            deployedContracts[0] = DeployData({name: "Gachachacha", contractAddress: addrs[0]});
        }
        {
            addrs[1] = address(new GuestFeature(ITypeCalculator(typecalculator)));
            deployedContracts[1] = DeployData({name: "Guest Feature", contractAddress: addrs[1]});
        }
        {
            addrs[2] = address(new SnackBreak());
            deployedContracts[2] = DeployData({name: "Snack Break", contractAddress: addrs[2]});
        }
        {
            addrs[3] = address(new CarrotHarvest());
            deployedContracts[3] = DeployData({name: "Carrot Harvest", contractAddress: addrs[3]});
        }

        _registerSofabbi(registry, addrs);

        return deployedContracts;
    }

    function _registerSofabbi(GachaTeamRegistry registry, address[4] memory addrs) internal {
        MonStats memory stats = MonStats({
            hp: 333,
            stamina: 5,
            speed: 175,
            attack: 180,
            defense: 201,
            specialAttack: 120,
            specialDefense: 269,
            type1: Type.Nature,
            type2: Type.None
        });
        uint256[] memory moves = new uint256[](4);
        moves[0] = 0x0030300000000000000000010000000000000000000000000000000000000000 | uint256(uint160(addrs[0]));
        moves[1] = 0x0030300000000000000000010000000000000000000000000000000000000000 | uint256(uint160(addrs[1]));
        moves[2] = 0x7807400000000000000000000000000000000000000000000000000000000000;
        moves[3] = 0x0030100000000000000000010000000000000000000000000000000000000000 | uint256(uint160(addrs[2]));
        uint256[] memory abilities = new uint256[](1);
        abilities[0] = (uint256(1) << 248) | uint256(uint160(addrs[3]));
        bytes32[] memory keys = new bytes32[](0);
        bytes32[] memory values = new bytes32[](0);
        registry.createMon(5, stats, moves, abilities, keys, values);
    }
}

contract SetupSofabbi is SofabbiDeploy {
    function run() external returns (DeployData[] memory deployedContracts) {
        vm.startBroadcast();
        deployedContracts = deploySofabbi(GachaTeamRegistry(vm.envAddress("GACHA_TEAM_REGISTRY")));
        vm.stopBroadcast();
    }
}
