// SPDX-License-Identifier: AGPL-3.0
// AUTO-GENERATED by processing/generateSolidity.py. Do not edit by hand.
pragma solidity ^0.8.0;

import {Script} from "forge-std/Script.sol";
import {DeployData} from "../DeployData.sol";
import {Type} from "../../src/Enums.sol";
import {MonStats} from "../../src/Structs.sol";
import {GachaTeamRegistry} from "../../src/game-layer/GachaTeamRegistry.sol";
import {BubbleBop} from "../../src/mons/ekineki/BubbleBop.sol";
import {NineNineNine} from "../../src/mons/ekineki/NineNineNine.sol";
import {Overflow} from "../../src/mons/ekineki/Overflow.sol";
import {SaviorComplex} from "../../src/mons/ekineki/SaviorComplex.sol";
import {SneakAttack} from "../../src/mons/ekineki/SneakAttack.sol";
import {ITypeCalculator} from "../../src/types/ITypeCalculator.sol";

abstract contract EkinekiDeploy is Script {
    function deployEkineki(GachaTeamRegistry registry) internal returns (DeployData[] memory) {
        DeployData[] memory deployedContracts = new DeployData[](5);

        // Cache commonly used addresses
        address typecalculator = vm.envAddress("TYPE_CALCULATOR");

        address[5] memory addrs;

        {
            addrs[0] = address(new BubbleBop(ITypeCalculator(typecalculator)));
            deployedContracts[0] = DeployData({name: "Bubble Bop", contractAddress: addrs[0]});
        }
        {
            addrs[1] = address(new SneakAttack(ITypeCalculator(typecalculator)));
            deployedContracts[1] = DeployData({name: "Sneak Attack", contractAddress: addrs[1]});
        }
        {
            addrs[2] = address(new NineNineNine());
            deployedContracts[2] = DeployData({name: "Nine Nine Nine", contractAddress: addrs[2]});
        }
        {
            addrs[3] = address(new Overflow(ITypeCalculator(typecalculator)));
            deployedContracts[3] = DeployData({name: "Overflow", contractAddress: addrs[3]});
        }
        {
            addrs[4] = address(new SaviorComplex());
            deployedContracts[4] = DeployData({name: "Savior Complex", contractAddress: addrs[4]});
        }

        _registerEkineki(registry, addrs);

        return deployedContracts;
    }

    function _registerEkineki(GachaTeamRegistry registry, address[5] memory addrs) internal {
        MonStats memory stats = MonStats({
            hp: 299,
            stamina: 5,
            speed: 266,
            attack: 130,
            defense: 180,
            specialAttack: 280,
            specialDefense: 175,
            type1: Type.Liquid,
            type2: Type.None
        });
        uint256[] memory moves = new uint256[](4);
        moves[0] = 0x0030300000000000000000010000000000000000000000000000000000000000 | uint256(uint160(addrs[0]));
        moves[1] = 0x0040f00000000000000000010000000000000000000000000000000000000000 | uint256(uint160(addrs[1]));
        moves[2] = 0x0030100000000000000000010000000000000000000000000000000000000000 | uint256(uint160(addrs[2]));
        moves[3] = 0x0030300000000000000000010000000000000000000000000000000000000000 | uint256(uint160(addrs[3]));
        uint256[] memory abilities = new uint256[](1);
        abilities[0] = uint256(uint160(addrs[4]));
        bytes32[] memory keys = new bytes32[](0);
        bytes32[] memory values = new bytes32[](0);
        registry.createMon(11, stats, moves, abilities, keys, values);
    }
}

contract SetupEkineki is EkinekiDeploy {
    function run() external returns (DeployData[] memory deployedContracts) {
        vm.startBroadcast();
        deployedContracts = deployEkineki(GachaTeamRegistry(vm.envAddress("GACHA_TEAM_REGISTRY")));
        vm.stopBroadcast();
    }
}
