// SPDX-License-Identifier: AGPL-3.0
// AUTO-GENERATED by processing/generateSolidity.py. Do not edit by hand.
pragma solidity ^0.8.0;

import {Script} from "forge-std/Script.sol";
import {DeployData} from "../DeployData.sol";
import {Type} from "../../src/Enums.sol";
import {MonStats} from "../../src/Structs.sol";
import {GachaTeamRegistry} from "../../src/game-layer/GachaTeamRegistry.sol";
import {IEffect} from "../../src/effects/IEffect.sol";
import {HeatBeacon} from "../../src/mons/embursa/HeatBeacon.sol";
import {HoneyBribe} from "../../src/mons/embursa/HoneyBribe.sol";
import {Q5} from "../../src/mons/embursa/Q5.sol";
import {SetAblaze} from "../../src/mons/embursa/SetAblaze.sol";
import {Tinderclaws} from "../../src/mons/embursa/Tinderclaws.sol";
import {ITypeCalculator} from "../../src/types/ITypeCalculator.sol";

abstract contract EmbursaDeploy is Script {
    function deployEmbursa(GachaTeamRegistry registry) internal returns (DeployData[] memory) {
        DeployData[] memory deployedContracts = new DeployData[](5);

        // Cache commonly used addresses
        address burnstatus = vm.envAddress("BURN_STATUS");
        address typecalculator = vm.envAddress("TYPE_CALCULATOR");

        address[5] memory addrs;

        {
            addrs[0] = address(new HoneyBribe());
            deployedContracts[0] = DeployData({name: "Honey Bribe", contractAddress: addrs[0]});
        }
        {
            addrs[1] = address(new SetAblaze(ITypeCalculator(typecalculator), IEffect(burnstatus)));
            deployedContracts[1] = DeployData({name: "Set Ablaze", contractAddress: addrs[1]});
        }
        {
            addrs[2] = address(new HeatBeacon(IEffect(burnstatus)));
            deployedContracts[2] = DeployData({name: "Heat Beacon", contractAddress: addrs[2]});
        }
        {
            addrs[3] = address(new Q5(ITypeCalculator(typecalculator)));
            deployedContracts[3] = DeployData({name: "Q5", contractAddress: addrs[3]});
        }
        {
            addrs[4] = address(new Tinderclaws(IEffect(burnstatus)));
            deployedContracts[4] = DeployData({name: "Tinderclaws", contractAddress: addrs[4]});
        }

        _registerEmbursa(registry, addrs);

        return deployedContracts;
    }

    function _registerEmbursa(GachaTeamRegistry registry, address[5] memory addrs) internal {
        MonStats memory stats = MonStats({
            hp: 420,
            stamina: 5,
            speed: 111,
            attack: 141,
            defense: 220,
            specialAttack: 190,
            specialDefense: 161,
            type1: Type.Fire,
            type2: Type.None
        });
        uint256[] memory moves = new uint256[](4);
        moves[0] = 0x00f0200000000000000000010000000000000000000000000000000000000000 | uint256(uint160(addrs[0]));
        moves[1] = 0x00f0300000000000000000010000000000000000000000000000000000000000 | uint256(uint160(addrs[1]));
        moves[2] = 0x00f0000000000000000000030000000000000000000000000000000000000000 | uint256(uint160(addrs[2]));
        moves[3] = 0x00f0200000000000000000010000000000000000000000000000000000000000 | uint256(uint160(addrs[3]));
        uint256[] memory abilities = new uint256[](1);
        abilities[0] = (uint256(1) << 248) | uint256(uint160(addrs[4]));
        bytes32[] memory keys = new bytes32[](0);
        bytes32[] memory values = new bytes32[](0);
        registry.createMon(7, stats, moves, abilities, keys, values);
    }
}

contract SetupEmbursa is EmbursaDeploy {
    function run() external returns (DeployData[] memory deployedContracts) {
        vm.startBroadcast();
        deployedContracts = deployEmbursa(GachaTeamRegistry(vm.envAddress("GACHA_TEAM_REGISTRY")));
        vm.stopBroadcast();
    }
}
