// SPDX-License-Identifier: AGPL-3.0
// AUTO-GENERATED by processing/generateSolidity.py. Do not edit by hand.
pragma solidity ^0.8.0;

import {Script} from "forge-std/Script.sol";
import {DeployData} from "../DeployData.sol";
import {Type} from "../../src/Enums.sol";
import {MonStats} from "../../src/Structs.sol";
import {GachaTeamRegistry} from "../../src/game-layer/GachaTeamRegistry.sol";
import {IEffect} from "../../src/effects/IEffect.sol";
import {ChosenOne} from "../../src/mons/glob/ChosenOne.sol";
import {GetSlippery} from "../../src/mons/glob/GetSlippery.sol";
import {HolyMolt} from "../../src/mons/glob/HolyMolt.sol";

abstract contract GlobDeploy is Script {
    function deployGlob(GachaTeamRegistry registry) internal returns (DeployData[] memory) {
        DeployData[] memory deployedContracts = new DeployData[](3);

        // Cache commonly used addresses
        address blessedstatus = vm.envAddress("BLESSED_STATUS");

        address[3] memory addrs;

        {
            addrs[0] = address(new HolyMolt(IEffect(blessedstatus)));
            deployedContracts[0] = DeployData({name: "Holy Molt", contractAddress: addrs[0]});
        }
        {
            addrs[1] = address(new GetSlippery());
            deployedContracts[1] = DeployData({name: "Get Slippery", contractAddress: addrs[1]});
        }
        {
            addrs[2] = address(new ChosenOne(IEffect(blessedstatus)));
            deployedContracts[2] = DeployData({name: "Chosen One", contractAddress: addrs[2]});
        }

        _registerGlob(registry, addrs);

        return deployedContracts;
    }

    function _registerGlob(GachaTeamRegistry registry, address[3] memory addrs) internal {
        MonStats memory stats = MonStats({
            hp: 301,
            stamina: 5,
            speed: 151,
            attack: 180,
            defense: 201,
            specialAttack: 115,
            specialDefense: 191,
            type1: Type.Liquid,
            type2: Type.Faith
        });
        uint256[] memory moves = new uint256[](4);
        moves[0] = 0x0040f00000000000000000010000000000000000000000000000000000000000 | uint256(uint160(addrs[0]));
        moves[1] = 0x5003200000000000000000000000000000000000000000000000000000000000;
        moves[2] = 0x5a09300000000000000000000000000000000000000000000000000000000000;
        moves[3] = 0x0030200000000000000000010000000000000000000000000000000000000000 | uint256(uint160(addrs[1]));
        uint256[] memory abilities = new uint256[](1);
        abilities[0] = uint256(uint160(addrs[2]));
        bytes32[] memory keys = new bytes32[](0);
        bytes32[] memory values = new bytes32[](0);
        registry.createMon(13, stats, moves, abilities, keys, values);
    }
}

contract SetupGlob is GlobDeploy {
    function run() external returns (DeployData[] memory deployedContracts) {
        vm.startBroadcast();
        deployedContracts = deployGlob(GachaTeamRegistry(vm.envAddress("GACHA_TEAM_REGISTRY")));
        vm.stopBroadcast();
    }
}
