// SPDX-License-Identifier: AGPL-3.0
// AUTO-GENERATED by processing/generateSolidity.py. Do not edit by hand.
pragma solidity ^0.8.0;

import {Script} from "forge-std/Script.sol";
import {DeployData} from "../DeployData.sol";
import {Type} from "../../src/Enums.sol";
import {MonStats} from "../../src/Structs.sol";
import {GachaTeamRegistry} from "../../src/game-layer/GachaTeamRegistry.sol";
import {IEffect} from "../../src/effects/IEffect.sol";
import {ChainExpansion} from "../../src/mons/inutia/ChainExpansion.sol";
import {HitAndDip} from "../../src/mons/inutia/HitAndDip.sol";
import {Initialize} from "../../src/mons/inutia/Initialize.sol";
import {Interweaving} from "../../src/mons/inutia/Interweaving.sol";
import {Sanctify} from "../../src/mons/inutia/Sanctify.sol";
import {ITypeCalculator} from "../../src/types/ITypeCalculator.sol";

abstract contract InutiaDeploy is Script {
    function deployInutia(GachaTeamRegistry registry) internal returns (DeployData[] memory) {
        DeployData[] memory deployedContracts = new DeployData[](5);

        // Cache commonly used addresses
        address typecalculator = vm.envAddress("TYPE_CALCULATOR");

        address[5] memory addrs;

        {
            addrs[0] = address(new ChainExpansion(ITypeCalculator(typecalculator)));
            deployedContracts[0] = DeployData({name: "Chain Expansion", contractAddress: addrs[0]});
        }
        {
            addrs[1] = address(new Initialize());
            deployedContracts[1] = DeployData({name: "Initialize", contractAddress: addrs[1]});
        }
        {
            addrs[2] = address(new HitAndDip(ITypeCalculator(typecalculator)));
            deployedContracts[2] = DeployData({name: "Hit And Dip", contractAddress: addrs[2]});
        }
        {
            addrs[3] = address(new Sanctify(IEffect(vm.envAddress("BLESSED_STATUS"))));
            deployedContracts[3] = DeployData({name: "Sanctify", contractAddress: addrs[3]});
        }
        {
            addrs[4] = address(new Interweaving());
            deployedContracts[4] = DeployData({name: "Interweaving", contractAddress: addrs[4]});
        }

        _registerInutia(registry, addrs);

        return deployedContracts;
    }

    function _registerInutia(GachaTeamRegistry registry, address[5] memory addrs) internal {
        MonStats memory stats = MonStats({
            hp: 351,
            stamina: 5,
            speed: 229,
            attack: 171,
            defense: 189,
            specialAttack: 175,
            specialDefense: 192,
            type1: Type.Faith,
            type2: Type.None
        });
        uint256[] memory moves = new uint256[](5);
        moves[0] = 0x0030100000000000000000010000000000000000000000000000000000000000 | uint256(uint160(addrs[0]));
        moves[1] = 0x0030200000000000000000010000000000000000000000000000000000000000 | uint256(uint160(addrs[1]));
        moves[2] = 0x5009200000000000000000000000000000000000000000000000000000000000;
        moves[3] = 0x0030200000000000000000050000000000000000000000000000000000000000 | uint256(uint160(addrs[2]));
        moves[4] = 0x0030200000000000000000010000000000000000000000000000000000000000 | uint256(uint160(addrs[3]));
        uint256[] memory abilities = new uint256[](1);
        abilities[0] = uint256(uint160(addrs[4]));
        bytes32[] memory keys = new bytes32[](0);
        bytes32[] memory values = new bytes32[](0);
        registry.createMon(1, stats, moves, abilities, keys, values);
    }
}

contract SetupInutia is InutiaDeploy {
    function run() external returns (DeployData[] memory deployedContracts) {
        vm.startBroadcast();
        deployedContracts = deployInutia(GachaTeamRegistry(vm.envAddress("GACHA_TEAM_REGISTRY")));
        vm.stopBroadcast();
    }
}
