// SPDX-License-Identifier: AGPL-3.0
// AUTO-GENERATED by processing/generateSolidity.py. Do not edit by hand.
pragma solidity ^0.8.0;

import {Script} from "forge-std/Script.sol";
import {DeployData} from "../DeployData.sol";
import {Type} from "../../src/Enums.sol";
import {MonStats} from "../../src/Structs.sol";
import {GachaTeamRegistry} from "../../src/game-layer/GachaTeamRegistry.sol";
import {ActusReus} from "../../src/mons/malalien/ActusReus.sol";
import {FoulLanguage} from "../../src/mons/malalien/FoulLanguage.sol";
import {TripleThink} from "../../src/mons/malalien/TripleThink.sol";
import {ITypeCalculator} from "../../src/types/ITypeCalculator.sol";

abstract contract MalalienDeploy is Script {
    function deployMalalien(GachaTeamRegistry registry) internal returns (DeployData[] memory) {
        DeployData[] memory deployedContracts = new DeployData[](3);

        address[3] memory addrs;

        {
            addrs[0] = address(new TripleThink());
            deployedContracts[0] = DeployData({name: "Triple Think", contractAddress: addrs[0]});
        }
        {
            addrs[1] = address(new FoulLanguage(ITypeCalculator(vm.envAddress("TYPE_CALCULATOR"))));
            deployedContracts[1] = DeployData({name: "Foul Language", contractAddress: addrs[1]});
        }
        {
            addrs[2] = address(new ActusReus());
            deployedContracts[2] = DeployData({name: "Actus Reus", contractAddress: addrs[2]});
        }

        _registerMalalien(registry, addrs);

        return deployedContracts;
    }

    function _registerMalalien(GachaTeamRegistry registry, address[3] memory addrs) internal {
        MonStats memory stats = MonStats({
            hp: 258,
            stamina: 5,
            speed: 308,
            attack: 121,
            defense: 125,
            specialAttack: 322,
            specialDefense: 151,
            type1: Type.Cyber,
            type2: Type.None
        });
        uint256[] memory moves = new uint256[](5);
        moves[0] = 0x0030200000000000000000010000000000000000000000000000000000000000 | uint256(uint160(addrs[0]));
        moves[1] = 0x644c300000000000000000000000000000000000000000000000000000000000;
        moves[2] = 0x504b30a000000000000000000000000000000000000000000000000000000000 | uint256(uint160(vm.envAddress("PANIC_STATUS")));
        moves[3] = 0x5a4d30a000000000000000000000000000000000000000000000000000000000 | uint256(uint160(vm.envAddress("SLEEP_STATUS")));
        moves[4] = 0x0030200000000000000000010000000000000000000000000000000000000000 | uint256(uint160(addrs[1]));
        uint256[] memory abilities = new uint256[](1);
        abilities[0] = (uint256(1) << 248) | uint256(uint160(addrs[2]));
        bytes32[] memory keys = new bytes32[](0);
        bytes32[] memory values = new bytes32[](0);
        registry.createMon(2, stats, moves, abilities, keys, values);
    }
}

contract SetupMalalien is MalalienDeploy {
    function run() external returns (DeployData[] memory deployedContracts) {
        vm.startBroadcast();
        deployedContracts = deployMalalien(GachaTeamRegistry(vm.envAddress("GACHA_TEAM_REGISTRY")));
        vm.stopBroadcast();
    }
}
