// SPDX-License-Identifier: AGPL-3.0
// AUTO-GENERATED by processing/generateSolidity.py. Do not edit by hand.
pragma solidity ^0.8.0;

import {Script} from "forge-std/Script.sol";
import {DeployData} from "../DeployData.sol";
import {Type} from "../../src/Enums.sol";
import {MonStats} from "../../src/Structs.sol";
import {GachaTeamRegistry} from "../../src/game-layer/GachaTeamRegistry.sol";
import {IEffect} from "../../src/effects/IEffect.sol";
import {ContagiousSlumber} from "../../src/mons/xmon/ContagiousSlumber.sol";
import {Dreamcatcher} from "../../src/mons/xmon/Dreamcatcher.sol";
import {InvokeTaboo} from "../../src/mons/xmon/InvokeTaboo.sol";
import {OldVengeance} from "../../src/mons/xmon/OldVengeance.sol";
import {Somniphobia} from "../../src/mons/xmon/Somniphobia.sol";
import {VitalSiphon} from "../../src/mons/xmon/VitalSiphon.sol";
import {ITypeCalculator} from "../../src/types/ITypeCalculator.sol";

abstract contract XmonDeploy is Script {
    function deployXmon(GachaTeamRegistry registry) internal returns (DeployData[] memory) {
        DeployData[] memory deployedContracts = new DeployData[](6);

        // Cache commonly used addresses
        address sleepstatus = vm.envAddress("SLEEP_STATUS");
        address typecalculator = vm.envAddress("TYPE_CALCULATOR");

        address[6] memory addrs;

        {
            addrs[0] = address(new ContagiousSlumber(IEffect(sleepstatus)));
            deployedContracts[0] = DeployData({name: "Contagious Slumber", contractAddress: addrs[0]});
        }
        {
            addrs[1] = address(new VitalSiphon(ITypeCalculator(typecalculator)));
            deployedContracts[1] = DeployData({name: "Vital Siphon", contractAddress: addrs[1]});
        }
        {
            addrs[2] = address(new Somniphobia());
            deployedContracts[2] = DeployData({name: "Somniphobia", contractAddress: addrs[2]});
        }
        {
            addrs[3] = address(new OldVengeance(ITypeCalculator(typecalculator)));
            deployedContracts[3] = DeployData({name: "Old Vengeance", contractAddress: addrs[3]});
        }
        {
            addrs[4] = address(new InvokeTaboo(IEffect(sleepstatus)));
            deployedContracts[4] = DeployData({name: "Invoke Taboo", contractAddress: addrs[4]});
        }
        {
            addrs[5] = address(new Dreamcatcher());
            deployedContracts[5] = DeployData({name: "Dreamcatcher", contractAddress: addrs[5]});
        }

        _registerXmon(registry, addrs);

        return deployedContracts;
    }

    function _registerXmon(GachaTeamRegistry registry, address[6] memory addrs) internal {
        MonStats memory stats = MonStats({
            hp: 311,
            stamina: 5,
            speed: 285,
            attack: 123,
            defense: 179,
            specialAttack: 222,
            specialDefense: 185,
            type1: Type.Cosmic,
            type2: Type.None
        });
        uint256[] memory moves = new uint256[](5);
        moves[0] = 0x0030200000000000000000010000000000000000000000000000000000000000 | uint256(uint160(addrs[0]));
        moves[1] = 0x0030200000000000000000010000000000000000000000000000000000000000 | uint256(uint160(addrs[1]));
        moves[2] = 0x0030100000000000000000010000000000000000000000000000000000000000 | uint256(uint160(addrs[2]));
        moves[3] = 0x0040400000000000000000010000000000000000000000000000000000000000 | uint256(uint160(addrs[3]));
        moves[4] = 0x0020100000000000000000010000000000000000000000000000000000000000 | uint256(uint160(addrs[4]));
        uint256[] memory abilities = new uint256[](1);
        abilities[0] = (uint256(1) << 248) | uint256(uint160(addrs[5]));
        bytes32[] memory keys = new bytes32[](0);
        bytes32[] memory values = new bytes32[](0);
        registry.createMon(10, stats, moves, abilities, keys, values);
    }
}

contract SetupXmon is XmonDeploy {
    function run() external returns (DeployData[] memory deployedContracts) {
        vm.startBroadcast();
        deployedContracts = deployXmon(GachaTeamRegistry(vm.envAddress("GACHA_TEAM_REGISTRY")));
        vm.stopBroadcast();
    }
}
