// SPDX-License-Identifier: AGPL-3.0
// AUTO-GENERATED by processing/generateSolidity.py. Do not edit by hand.
pragma solidity ^0.8.0;

import {Script} from "forge-std/Script.sol";
import {DeployData} from "../DeployData.sol";
import {Type} from "../../src/Enums.sol";
import {MonStats} from "../../src/Structs.sol";
import {GachaTeamRegistry} from "../../src/game-layer/GachaTeamRegistry.sol";
import {IEffect} from "../../src/effects/IEffect.sol";
import {EternalGrudge} from "../../src/mons/ghouliath/EternalGrudge.sol";
import {GraveAffliction} from "../../src/mons/ghouliath/GraveAffliction.sol";
import {InfernalFlame} from "../../src/mons/ghouliath/InfernalFlame.sol";
import {RiseFromTheGrave} from "../../src/mons/ghouliath/RiseFromTheGrave.sol";
import {WitherAway} from "../../src/mons/ghouliath/WitherAway.sol";
import {ITypeCalculator} from "../../src/types/ITypeCalculator.sol";

abstract contract GhouliathDeploy is Script {
    function deployGhouliath(GachaTeamRegistry registry) internal returns (DeployData[] memory) {
        DeployData[] memory deployedContracts = new DeployData[](5);

        // Cache commonly used addresses
        address typecalculator = vm.envAddress("TYPE_CALCULATOR");

        address[5] memory addrs;

        {
            addrs[0] = address(new EternalGrudge());
            deployedContracts[0] = DeployData({name: "Eternal Grudge", contractAddress: addrs[0]});
        }
        {
            addrs[1] = address(new InfernalFlame(ITypeCalculator(typecalculator), IEffect(vm.envAddress("BURN_STATUS"))));
            deployedContracts[1] = DeployData({name: "Infernal Flame", contractAddress: addrs[1]});
        }
        {
            addrs[2] = address(new WitherAway(ITypeCalculator(typecalculator), IEffect(vm.envAddress("PANIC_STATUS"))));
            deployedContracts[2] = DeployData({name: "Wither Away", contractAddress: addrs[2]});
        }
        {
            addrs[3] = address(new GraveAffliction());
            deployedContracts[3] = DeployData({name: "Grave Affliction", contractAddress: addrs[3]});
        }
        {
            addrs[4] = address(new RiseFromTheGrave());
            deployedContracts[4] = DeployData({name: "Rise From The Grave", contractAddress: addrs[4]});
        }

        _registerGhouliath(registry, addrs);

        return deployedContracts;
    }

    function _registerGhouliath(GachaTeamRegistry registry, address[5] memory addrs) internal {
        MonStats memory stats = MonStats({
            hp: 303,
            stamina: 5,
            speed: 181,
            attack: 157,
            defense: 202,
            specialAttack: 151,
            specialDefense: 202,
            type1: Type.Yin,
            type2: Type.Fire
        });
        uint256[] memory moves = new uint256[](5);
        moves[0] = 0x0040200000000000000000010000000000000000000000000000000000000000 | uint256(uint160(addrs[0]));
        moves[1] = 0x0030200000000000000000010000000000000000000000000000000000000000 | uint256(uint160(addrs[1]));
        moves[2] = 0x0030300000000000000000010000000000000000000000000000000000000000 | uint256(uint160(addrs[2]));
        moves[3] = 0x5a00200000000000000000000000000000000000000000000000000000000000;
        moves[4] = 0x0030200000000000000000030000000000000000000000000000000000000000 | uint256(uint160(addrs[3]));
        uint256[] memory abilities = new uint256[](1);
        abilities[0] = uint256(uint160(addrs[4]));
        bytes32[] memory keys = new bytes32[](0);
        bytes32[] memory values = new bytes32[](0);
        registry.createMon(0, stats, moves, abilities, keys, values);
    }
}

contract SetupGhouliath is GhouliathDeploy {
    function run() external returns (DeployData[] memory deployedContracts) {
        vm.startBroadcast();
        deployedContracts = deployGhouliath(GachaTeamRegistry(vm.envAddress("GACHA_TEAM_REGISTRY")));
        vm.stopBroadcast();
    }
}
