// SPDX-License-Identifier: AGPL-3.0
// AUTO-GENERATED by processing/generateSolidity.py. Do not edit by hand.
pragma solidity ^0.8.0;

import {Script} from "forge-std/Script.sol";
import {DeployData} from "../DeployData.sol";
import {Type} from "../../src/Enums.sol";
import {MonStats} from "../../src/Structs.sol";
import {GachaTeamRegistry} from "../../src/game-layer/GachaTeamRegistry.sol";
import {IEffect} from "../../src/effects/IEffect.sol";
import {Adaptor} from "../../src/mons/nirvamma/Adaptor.sol";
import {Chronoffense} from "../../src/mons/nirvamma/Chronoffense.sol";
import {HardReset} from "../../src/mons/nirvamma/HardReset.sol";
import {ModalBolt} from "../../src/mons/nirvamma/ModalBolt.sol";

abstract contract NirvammaDeploy is Script {
    function deployNirvamma(GachaTeamRegistry registry) internal returns (DeployData[] memory) {
        DeployData[] memory deployedContracts = new DeployData[](4);

        address[4] memory addrs;

        {
            addrs[0] = address(new HardReset());
            deployedContracts[0] = DeployData({name: "Hard Reset", contractAddress: addrs[0]});
        }
        {
            addrs[1] = address(new Chronoffense());
            deployedContracts[1] = DeployData({name: "Chronoffense", contractAddress: addrs[1]});
        }
        {
            addrs[2] = address(new ModalBolt(IEffect(vm.envAddress("BURN_STATUS")), IEffect(vm.envAddress("FROSTBITE_STATUS")), IEffect(vm.envAddress("ZAP_STATUS"))));
            deployedContracts[2] = DeployData({name: "Modal Bolt", contractAddress: addrs[2]});
        }
        {
            addrs[3] = address(new Adaptor());
            deployedContracts[3] = DeployData({name: "Adaptor", contractAddress: addrs[3]});
        }

        _registerNirvamma(registry, addrs);

        return deployedContracts;
    }

    function _registerNirvamma(GachaTeamRegistry registry, address[4] memory addrs) internal {
        MonStats memory stats = MonStats({
            hp: 373,
            stamina: 5,
            speed: 177,
            attack: 202,
            defense: 168,
            specialAttack: 140,
            specialDefense: 202,
            type1: Type.Math,
            type2: Type.None
        });
        uint256[] memory moves = new uint256[](4);
        moves[0] = 0x0030200000000000000000010000000000000000000000000000000000000000 | uint256(uint160(addrs[0]));
        moves[1] = 0x500b314000000000000000000000000000000000000000000000000000000000 | uint256(uint160(vm.envAddress("PANIC_STATUS")));
        moves[2] = 0x0030200000000000000000010000000000000000000000000000000000000000 | uint256(uint160(addrs[1]));
        moves[3] = 0x0030300000000000000000010000000000000000000000000000000000000000 | uint256(uint160(addrs[2]));
        uint256[] memory abilities = new uint256[](1);
        abilities[0] = (uint256(1) << 248) | uint256(uint160(addrs[3]));
        bytes32[] memory keys = new bytes32[](0);
        bytes32[] memory values = new bytes32[](0);
        registry.createMon(12, stats, moves, abilities, keys, values);
    }
}

contract SetupNirvamma is NirvammaDeploy {
    function run() external returns (DeployData[] memory deployedContracts) {
        vm.startBroadcast();
        deployedContracts = deployNirvamma(GachaTeamRegistry(vm.envAddress("GACHA_TEAM_REGISTRY")));
        vm.stopBroadcast();
    }
}
