// SPDX-License-Identifier: AGPL-3.0
// AUTO-GENERATED by processing/generateSolidity.py. Do not edit by hand.
pragma solidity ^0.8.0;

import {Script} from "forge-std/Script.sol";
import {DeployData} from "../DeployData.sol";
import {Type} from "../../src/Enums.sol";
import {MonStats} from "../../src/Structs.sol";
import {GachaTeamRegistry} from "../../src/game-layer/GachaTeamRegistry.sol";
import {IEffect} from "../../src/effects/IEffect.sol";
import {BigBellow} from "../../src/mons/aurox/BigBellow.sol";
import {BullRush} from "../../src/mons/aurox/BullRush.sol";
import {GildedRecovery} from "../../src/mons/aurox/GildedRecovery.sol";
import {IronWall} from "../../src/mons/aurox/IronWall.sol";
import {UpOnly} from "../../src/mons/aurox/UpOnly.sol";
import {VolatilePunch} from "../../src/mons/aurox/VolatilePunch.sol";
import {ITypeCalculator} from "../../src/types/ITypeCalculator.sol";

abstract contract AuroxDeploy is Script {
    function deployAurox(GachaTeamRegistry registry) internal returns (DeployData[] memory) {
        DeployData[] memory deployedContracts = new DeployData[](6);

        // Cache commonly used addresses
        address typecalculator = vm.envAddress("TYPE_CALCULATOR");

        address[6] memory addrs;

        {
            addrs[0] = address(new VolatilePunch(ITypeCalculator(typecalculator), IEffect(vm.envAddress("BURN_STATUS")), IEffect(vm.envAddress("FROSTBITE_STATUS"))));
            deployedContracts[0] = DeployData({name: "Volatile Punch", contractAddress: addrs[0]});
        }
        {
            addrs[1] = address(new GildedRecovery());
            deployedContracts[1] = DeployData({name: "Gilded Recovery", contractAddress: addrs[1]});
        }
        {
            addrs[2] = address(new IronWall());
            deployedContracts[2] = DeployData({name: "Iron Wall", contractAddress: addrs[2]});
        }
        {
            addrs[3] = address(new BullRush(ITypeCalculator(typecalculator)));
            deployedContracts[3] = DeployData({name: "Bull Rush", contractAddress: addrs[3]});
        }
        {
            addrs[4] = address(new BigBellow());
            deployedContracts[4] = DeployData({name: "Big Bellow", contractAddress: addrs[4]});
        }
        {
            addrs[5] = address(new UpOnly());
            deployedContracts[5] = DeployData({name: "Up Only", contractAddress: addrs[5]});
        }

        _registerAurox(registry, addrs);

        return deployedContracts;
    }

    function _registerAurox(GachaTeamRegistry registry, address[6] memory addrs) internal {
        MonStats memory stats = MonStats({
            hp: 400,
            stamina: 5,
            speed: 100,
            attack: 150,
            defense: 230,
            specialAttack: 100,
            specialDefense: 220,
            type1: Type.Metal,
            type2: Type.None
        });
        uint256[] memory moves = new uint256[](5);
        moves[0] = 0x0030300000000000000000010000000000000000000000000000000000000000 | uint256(uint160(addrs[0]));
        moves[1] = 0x0030200000000000000000010000000000000000000000000000000000000000 | uint256(uint160(addrs[1]));
        moves[2] = 0x0030300000000000000000010000000000000000000000000000000000000000 | uint256(uint160(addrs[2]));
        moves[3] = 0x0030200000000000000000010000000000000000000000000000000000000000 | uint256(uint160(addrs[3]));
        moves[4] = 0x0030100000000000000000010000000000000000000000000000000000000000 | uint256(uint160(addrs[4]));
        uint256[] memory abilities = new uint256[](1);
        abilities[0] = (uint256(1) << 248) | uint256(uint160(addrs[5]));
        bytes32[] memory keys = new bytes32[](0);
        bytes32[] memory values = new bytes32[](0);
        registry.createMon(9, stats, moves, abilities, keys, values);
    }
}

contract SetupAurox is AuroxDeploy {
    function run() external returns (DeployData[] memory deployedContracts) {
        vm.startBroadcast();
        deployedContracts = deployAurox(GachaTeamRegistry(vm.envAddress("GACHA_TEAM_REGISTRY")));
        vm.stopBroadcast();
    }
}
