// SPDX-License-Identifier: AGPL-3.0
// AUTO-GENERATED by processing/generateSolidity.py. Do not edit by hand.
pragma solidity ^0.8.0;

import {Script} from "forge-std/Script.sol";
import {DeployData} from "../DeployData.sol";
import {Type} from "../../src/Enums.sol";
import {MonStats} from "../../src/Structs.sol";
import {GachaTeamRegistry} from "../../src/game-layer/GachaTeamRegistry.sol";
import {IEffect} from "../../src/effects/IEffect.sol";
import {Storm} from "../../src/effects/battlefield/Storm.sol";
import {CloudStrike} from "../../src/mons/mulong/CloudStrike.sol";
import {KingsLeisure} from "../../src/mons/mulong/KingsLeisure.sol";
import {KingsRespite} from "../../src/mons/mulong/KingsRespite.sol";
import {SummonStorm} from "../../src/mons/mulong/SummonStorm.sol";
import {ITypeCalculator} from "../../src/types/ITypeCalculator.sol";

abstract contract MulongDeploy is Script {
    function deployMulong(GachaTeamRegistry registry) internal returns (DeployData[] memory) {
        DeployData[] memory deployedContracts = new DeployData[](4);

        // Cache commonly used addresses
        address storm = vm.envAddress("STORM");

        address[4] memory addrs;

        {
            addrs[0] = address(new SummonStorm(Storm(storm)));
            deployedContracts[0] = DeployData({name: "Summon Storm", contractAddress: addrs[0]});
        }
        {
            addrs[1] = address(new KingsRespite(ITypeCalculator(vm.envAddress("TYPE_CALCULATOR"))));
            deployedContracts[1] = DeployData({name: "King's Respite", contractAddress: addrs[1]});
        }
        {
            addrs[2] = address(new CloudStrike(Storm(storm), IEffect(vm.envAddress("FROSTBITE_STATUS"))));
            deployedContracts[2] = DeployData({name: "Cloud Strike", contractAddress: addrs[2]});
        }
        {
            addrs[3] = address(new KingsLeisure());
            deployedContracts[3] = DeployData({name: "King's Leisure", contractAddress: addrs[3]});
        }

        _registerMulong(registry, addrs);

        return deployedContracts;
    }

    function _registerMulong(GachaTeamRegistry registry, address[4] memory addrs) internal {
        MonStats memory stats = MonStats({
            hp: 368,
            stamina: 5,
            speed: 290,
            attack: 115,
            defense: 188,
            specialAttack: 288,
            specialDefense: 138,
            type1: Type.Air,
            type2: Type.Lightning
        });
        uint256[] memory moves = new uint256[](4);
        moves[0] = 0x0030000000000000000000010000000000000000000000000000000000000000 | uint256(uint160(addrs[0]));
        moves[1] = 0x0030200000000000000000010000000000000000000000000000000000000000 | uint256(uint160(addrs[1]));
        moves[2] = 0x7848314000000000000000000000000000000000000000000000000000000000 | uint256(uint160(vm.envAddress("ZAP_STATUS")));
        moves[3] = 0x0030200000000000000000010000000000000000000000000000000000000000 | uint256(uint160(addrs[2]));
        uint256[] memory abilities = new uint256[](1);
        abilities[0] = uint256(uint160(addrs[3]));
        bytes32[] memory keys = new bytes32[](0);
        bytes32[] memory values = new bytes32[](0);
        registry.createMon(14, stats, moves, abilities, keys, values);
    }
}

contract SetupMulong is MulongDeploy {
    function run() external returns (DeployData[] memory deployedContracts) {
        vm.startBroadcast();
        deployedContracts = deployMulong(GachaTeamRegistry(vm.envAddress("GACHA_TEAM_REGISTRY")));
        vm.stopBroadcast();
    }
}
