// SPDX-License-Identifier: AGPL-3.0
// AUTO-GENERATED by processing/generateSolidity.py. Do not edit by hand.
pragma solidity ^0.8.0;

import {Script} from "forge-std/Script.sol";
import {DeployData} from "../DeployData.sol";
import {Type} from "../../src/Enums.sol";
import {MonStats} from "../../src/Structs.sol";
import {GachaTeamRegistry} from "../../src/game-layer/GachaTeamRegistry.sol";
import {Baselight} from "../../src/mons/iblivion/Baselight.sol";
import {Brightback} from "../../src/mons/iblivion/Brightback.sol";
import {Loop} from "../../src/mons/iblivion/Loop.sol";
import {Renormalize} from "../../src/mons/iblivion/Renormalize.sol";
import {UnboundedStrike} from "../../src/mons/iblivion/UnboundedStrike.sol";
import {ITypeCalculator} from "../../src/types/ITypeCalculator.sol";

abstract contract IblivionDeploy is Script {
    function deployIblivion(GachaTeamRegistry registry) internal returns (DeployData[] memory) {
        DeployData[] memory deployedContracts = new DeployData[](5);

        // Cache commonly used addresses
        address typecalculator = vm.envAddress("TYPE_CALCULATOR");

        address[5] memory addrs;

        {
            addrs[0] = address(new Baselight());
            deployedContracts[0] = DeployData({name: "Baselight", contractAddress: addrs[0]});
        }
        {
            addrs[1] = address(new UnboundedStrike(ITypeCalculator(typecalculator), Baselight(addrs[0])));
            deployedContracts[1] = DeployData({name: "Unbounded Strike", contractAddress: addrs[1]});
        }
        {
            addrs[2] = address(new Loop(Baselight(addrs[0])));
            deployedContracts[2] = DeployData({name: "Loop", contractAddress: addrs[2]});
        }
        {
            addrs[3] = address(new Brightback(ITypeCalculator(typecalculator), Baselight(addrs[0])));
            deployedContracts[3] = DeployData({name: "Brightback", contractAddress: addrs[3]});
        }
        {
            addrs[4] = address(new Renormalize(Baselight(addrs[0]), Loop(addrs[2])));
            deployedContracts[4] = DeployData({name: "Renormalize", contractAddress: addrs[4]});
        }

        _registerIblivion(registry, addrs);

        return deployedContracts;
    }

    function _registerIblivion(GachaTeamRegistry registry, address[5] memory addrs) internal {
        MonStats memory stats = MonStats({
            hp: 277,
            stamina: 5,
            speed: 256,
            attack: 199,
            defense: 164,
            specialAttack: 180,
            specialDefense: 168,
            type1: Type.Yang,
            type2: Type.Air
        });
        uint256[] memory moves = new uint256[](4);
        moves[0] = 0x0030f00000000000000000010000000000000000000000000000000000000000 | uint256(uint160(addrs[1]));
        moves[1] = 0x0030100000000000000000010000000000000000000000000000000000000000 | uint256(uint160(addrs[2]));
        moves[2] = 0x0030200000000000000000010000000000000000000000000000000000000000 | uint256(uint160(addrs[3]));
        moves[3] = 0x0020000000000000000000010000000000000000000000000000000000000000 | uint256(uint160(addrs[4]));
        uint256[] memory abilities = new uint256[](1);
        abilities[0] = uint256(uint160(addrs[0]));
        bytes32[] memory keys = new bytes32[](0);
        bytes32[] memory values = new bytes32[](0);
        registry.createMon(3, stats, moves, abilities, keys, values);
    }
}

contract SetupIblivion is IblivionDeploy {
    function run() external returns (DeployData[] memory deployedContracts) {
        vm.startBroadcast();
        deployedContracts = deployIblivion(GachaTeamRegistry(vm.envAddress("GACHA_TEAM_REGISTRY")));
        vm.stopBroadcast();
    }
}
