// SPDX-License-Identifier: AGPL-3.0
// AUTO-GENERATED by processing/generateSolidity.py. Do not edit by hand.
pragma solidity ^0.8.0;

import {Script} from "forge-std/Script.sol";
import {DeployData} from "../DeployData.sol";
import {Type} from "../../src/Enums.sol";
import {MonStats} from "../../src/Structs.sol";
import {GachaTeamRegistry} from "../../src/game-layer/GachaTeamRegistry.sol";
import {IEffect} from "../../src/effects/IEffect.sol";
import {Deadlift} from "../../src/mons/pengym/Deadlift.sol";
import {DeepFreeze} from "../../src/mons/pengym/DeepFreeze.sol";
import {PistolSquat} from "../../src/mons/pengym/PistolSquat.sol";
import {PostWorkout} from "../../src/mons/pengym/PostWorkout.sol";
import {ITypeCalculator} from "../../src/types/ITypeCalculator.sol";

abstract contract PengymDeploy is Script {
    function deployPengym(GachaTeamRegistry registry) internal returns (DeployData[] memory) {
        DeployData[] memory deployedContracts = new DeployData[](4);

        // Cache commonly used addresses
        address typecalculator = vm.envAddress("TYPE_CALCULATOR");

        address[4] memory addrs;

        {
            addrs[0] = address(new Deadlift());
            deployedContracts[0] = DeployData({name: "Deadlift", contractAddress: addrs[0]});
        }
        {
            addrs[1] = address(new DeepFreeze(ITypeCalculator(typecalculator), IEffect(vm.envAddress("FROSTBITE_STATUS"))));
            deployedContracts[1] = DeployData({name: "Deep Freeze", contractAddress: addrs[1]});
        }
        {
            addrs[2] = address(new PistolSquat(ITypeCalculator(typecalculator)));
            deployedContracts[2] = DeployData({name: "Pistol Squat", contractAddress: addrs[2]});
        }
        {
            addrs[3] = address(new PostWorkout());
            deployedContracts[3] = DeployData({name: "Post-Workout", contractAddress: addrs[3]});
        }

        _registerPengym(registry, addrs);

        return deployedContracts;
    }

    function _registerPengym(GachaTeamRegistry registry, address[4] memory addrs) internal {
        MonStats memory stats = MonStats({
            hp: 371,
            stamina: 5,
            speed: 149,
            attack: 212,
            defense: 191,
            specialAttack: 233,
            specialDefense: 172,
            type1: Type.Ice,
            type2: Type.None
        });
        uint256[] memory moves = new uint256[](4);
        moves[0] = 0x00c6064000000000000000000000000000000000000000000000000000000000 | uint256(uint160(vm.envAddress("FROSTBITE_STATUS")));
        moves[1] = 0x0030200000000000000000010000000000000000000000000000000000000000 | uint256(uint160(addrs[0]));
        moves[2] = 0x0030300000000000000000010000000000000000000000000000000000000000 | uint256(uint160(addrs[1]));
        moves[3] = 0x0020200000000000000000010000000000000000000000000000000000000000 | uint256(uint160(addrs[2]));
        uint256[] memory abilities = new uint256[](1);
        abilities[0] = (uint256(1) << 248) | uint256(uint160(addrs[3]));
        bytes32[] memory keys = new bytes32[](0);
        bytes32[] memory values = new bytes32[](0);
        registry.createMon(6, stats, moves, abilities, keys, values);
    }
}

contract SetupPengym is PengymDeploy {
    function run() external returns (DeployData[] memory deployedContracts) {
        vm.startBroadcast();
        deployedContracts = deployPengym(GachaTeamRegistry(vm.envAddress("GACHA_TEAM_REGISTRY")));
        vm.stopBroadcast();
    }
}
