//! Loop-driven mock moves — the T2 harness that stays entirely in `strategies-rs` (never
//! regenerated by the transpiler, so it survives a re-transpile) and touches no Solidity.
//!
//! A mock move is a normal INLINE move (the engine runs it generically). Each turn, before the
//! pilots decide, the game loop recomputes the mock's power from live state and writes the packed
//! word into `battleConfig[bk].pXTeam[mon].moves[lane]` — so conditional-power logic lives here,
//! and the engine just runs a standard attack at the computed power. Custom post-effects (steal
//! stamina, self-burn, recoil) apply via the engine's mutators after execute (added incrementally).
//!
//! Inline word layout: [basePower:8|moveClass:2|priority:2|moveType:4|stamina:4|effectAccuracy:8|_:68|effect:160].

use chomp_engine::Enums::{MonStateIndexName, MoveClass, Type};
use chomp_engine::Structs::Mon;
use chomp_rt::{Address, B256, U256};

use crate::analysis::{fold, MonStat};
use crate::arena::build_specs;
use crate::game::{run_games_instrumented, GameSpec};
use crate::roster::{self, Roster};
use crate::sim::Sim;
use crate::view::{active_mon_indices, ko_bitmap, mon_skip_turn, mon_state, mon_value, Seat, VCPU, VOPP};

/// Pack an inline move word from its fields.
pub fn pack_word(power: u32, class: u32, priority: u32, mtype: u32, stamina: u32, eff_acc: u32, effect: U256) -> U256 {
    (U256::from(power & 0xFF) << 248)
        | (U256::from(class & 0x3) << 246)
        | (U256::from(priority & 0x3) << 244)
        | (U256::from((mtype & 0xF) as u64) << 240)
        | (U256::from(stamina & 0xF) << 236)
        | (U256::from(eff_acc & 0xFF) << 228)
        | effect
}

/// How a mock move's base power is computed from live state, from the acting side's perspective.
#[derive(Clone, Copy, Debug)]
pub enum PowerRule {
    Fixed(u32),
    /// Collapse: base + per × (target's stamina missing from max), capped.
    OppMissingStamina { base: u32, per: u32, cap: u32 },
    /// Killing Blow: base, +bonus if ≥ threshold of the opponent's team is KO'd.
    OppKOs { base: u32, bonus: u32, threshold: u32 },
    /// All In: base + per × the actor's current stamina, capped.
    SelfStamina { base: u32, per: u32, cap: u32 },
    /// Lucid Nightmare: base, ×1.5 if the target is asleep (skips its turn).
    X15IfTargetAsleep { base: u32 },
}

#[derive(Clone)]
pub struct MockMove {
    pub name: &'static str,
    pub mon: &'static str,
    /// Which of the mon's 4 lanes the mock replaces for the A/B.
    pub lane: usize,
    pub mtype: Type,
    pub mclass: MoveClass,
    pub stamina: u8,
    pub priority: u8,
    pub eff_acc: u8,
    /// An existing effect contract to attach on hit (e.g. FrostbiteStatus), or None.
    pub effect: Option<&'static str>,
    pub power: PowerRule,
}

impl MockMove {
    fn effect_word(&self) -> U256 {
        match self.effect {
            Some(name) => addr_to_word(roster::addr_of(name)),
            None => U256::ZERO,
        }
    }
    /// A nominal word (used at draft time and as the pilot's decision-time estimate).
    fn nominal_word(&self) -> U256 {
        let base = match self.power {
            PowerRule::Fixed(p) => p,
            PowerRule::OppMissingStamina { base, .. } => base,
            PowerRule::OppKOs { base, .. } => base,
            PowerRule::SelfStamina { base, .. } => base,
            PowerRule::X15IfTargetAsleep { base } => base,
        };
        self.word_for(base)
    }
    fn word_for(&self, power: u32) -> U256 {
        pack_word(
            power.min(255),
            self.mclass as u32,
            self.priority as u32,
            self.mtype as u32,
            self.stamina as u32,
            self.eff_acc as u32,
            self.effect_word(),
        )
    }
}

fn addr_to_word(a: Address) -> U256 {
    let mut b = [0u8; 32];
    b[12..].copy_from_slice(a.as_slice());
    U256::from_be_bytes::<32>(b)
}

/// Compute the mock's base power from the acting seat's live state.
fn compute_power(sim: &mut Sim, seat: Seat, bk: B256, opp_active: usize, self_active: usize, rule: PowerRule) -> u32 {
    match rule {
        PowerRule::Fixed(p) => p,
        PowerRule::OppMissingStamina { base, per, cap } => {
            let max = mon_value(sim, seat, bk, VOPP, opp_active, MonStateIndexName::Stamina);
            let cur = max + mon_state(sim, seat, bk, VOPP, opp_active, MonStateIndexName::Stamina);
            let missing = (max - cur).max(0);
            (base as i64 + per as i64 * missing).min(cap as i64).max(0) as u32
        }
        PowerRule::OppKOs { base, bonus, threshold } => {
            let ko = ko_bitmap(sim, seat, bk, VOPP);
            if ko.count_ones() >= threshold { base + bonus } else { base }
        }
        PowerRule::SelfStamina { base, per, cap } => {
            let bs = mon_value(sim, seat, bk, VCPU, self_active, MonStateIndexName::Stamina);
            let ds = mon_state(sim, seat, bk, VCPU, self_active, MonStateIndexName::Stamina);
            let cur = (bs + ds).max(0);
            (base as i64 + per as i64 * cur).min(cap as i64).max(0) as u32
        }
        PowerRule::X15IfTargetAsleep { base } => {
            if mon_skip_turn(sim, seat, bk, VOPP, opp_active) { base * 3 / 2 } else { base }
        }
    }
}

/// Write a move word into live battle state for a physical side's mon lane.
fn write_word(sim: &mut Sim, bk: B256, phys: u64, mon_slot: usize, lane: usize, word: U256) {
    let cfg = sim.world.Engine.battleConfig.get_mut(&bk);
    let team = if phys == 0 { &mut cfg.p0Team } else { &mut cfg.p1Team };
    team.get_mut(&U256::from(mon_slot as u64)).moves[lane] = word;
}

// The instrumented mock loop lives in game.rs (needs the private seat/decide helpers); this module
// owns the move definitions, power math, and the A/B driver.

/// Build the A/B: baseline (real kit) vs the mock swapped into `mock.lane` of `mock.mon`, on the
/// same drafts. Returns (baseline, mocked) stats for the mock mon.
pub fn run_mock_ab(roster: &Roster, mock: &MockMove, games: usize, wseed: u32, seed_base: u32, threads: usize) -> (MonStat, MonStat) {
    let book = roster::address_book();
    let target_id = roster.mons.iter().find(|m| m.name == mock.mon).expect("mock mon in roster").id;

    // Baseline.
    let (specs, _) = build_specs(roster, games, wseed, seed_base);
    let base = fold(&run_games_instrumented(&specs, &book, threads));

    // Mocked: swap the lane's word to the mock's nominal, run the mock-aware loop that repacks it.
    let (mut mspecs, _) = build_specs(roster, games, wseed, seed_base);
    for spec in &mut mspecs {
        swap_lane(spec, target_id, mock);
    }
    let mocked = fold(&crate::game::run_games_mock(&mspecs, &book, threads, target_id, mock.lane, mock.clone()));

    let empty = MonStat::default();
    (
        base.per_mon.get(&target_id).cloned().unwrap_or_else(|| empty.clone()),
        mocked.per_mon.get(&target_id).cloned().unwrap_or(empty),
        )
}

fn swap_lane(spec: &mut GameSpec, target_id: u32, mock: &MockMove) {
    let w = mock.nominal_word();
    for slot in 0..spec.p0_ids.len() {
        if spec.p0_ids[slot] == target_id {
            set_team_lane(&mut spec.p0_team[slot], mock.lane, w);
        }
    }
    for slot in 0..spec.p1_ids.len() {
        if spec.p1_ids[slot] == target_id {
            set_team_lane(&mut spec.p1_team[slot], mock.lane, w);
        }
    }
}

fn set_team_lane(mon: &mut Mon, lane: usize, word: U256) {
    if lane < mon.moves.len() {
        mon.moves[lane] = word;
    }
}

/// The per-turn repack, called from the mock loop: for each acting side whose active mon is the
/// mock mon, recompute the mock's power from that side's perspective and write the word.
pub fn repack_turn(sim: &mut Sim, bk: B256, spec: &GameSpec, target_id: u32, lane: usize, mock: &MockMove) {
    let obs = Seat { cpu: 1 };
    let (p0a, p1a) = active_mon_indices(sim, obs, bk);
    if spec.p0_ids.get(p0a) == Some(&target_id) {
        let seat = Seat { cpu: 0 };
        let pow = compute_power(sim, seat, bk, /*opp*/ p1a, /*self*/ p0a, mock.power);
        write_word(sim, bk, 0, p0a, lane, mock.word_for(pow));
    }
    if spec.p1_ids.get(p1a) == Some(&target_id) {
        let seat = Seat { cpu: 1 };
        let pow = compute_power(sim, seat, bk, /*opp*/ p0a, /*self*/ p1a, mock.power);
        write_word(sim, bk, 1, p1a, lane, mock.word_for(pow));
    }
}

/// The five power-repack mocks validated in this first batch.
pub fn batch1() -> Vec<MockMove> {
    vec![
        MockMove { name: "Collapse", mon: "Xmon", lane: 3, mtype: Type::Cosmic, mclass: MoveClass::Special, stamina: 3, priority: 0, eff_acc: 0, effect: None, power: PowerRule::OppMissingStamina { base: 40, per: 20, cap: 140 } },
        MockMove { name: "Killing Blow", mon: "Ekineki", lane: 2, mtype: Type::Liquid, mclass: MoveClass::Special, stamina: 4, priority: 0, eff_acc: 0, effect: None, power: PowerRule::OppKOs { base: 100, bonus: 50, threshold: 2 } },
        MockMove { name: "All In", mon: "Sofabbi", lane: 3, mtype: Type::Nature, mclass: MoveClass::Physical, stamina: 3, priority: 0, eff_acc: 0, effect: None, power: PowerRule::SelfStamina { base: 90, per: 20, cap: 200 } },
        MockMove { name: "Lucid Nightmare", mon: "Xmon", lane: 2, mtype: Type::Cosmic, mclass: MoveClass::Special, stamina: 3, priority: 0, eff_acc: 0, effect: None, power: PowerRule::X15IfTargetAsleep { base: 90 } },
        MockMove { name: "Cold Front", mon: "Pengym", lane: 0, mtype: Type::Ice, mclass: MoveClass::Special, stamina: 2, priority: 0, eff_acc: 100, effect: Some("FrostbiteStatus"), power: PowerRule::Fixed(70) },
    ]
}
