#!/usr/bin/env python3
"""Generate src/types/TypeCalcLib.sol from drool/types.csv.

drool/types.csv is the single source of truth for type effectiveness. This packs the
N×N multiplier grid (N = number of real types, in enum order) into two uint256 words
and writes the TypeCalcLib library. CSV multipliers map: 0→0 (immune), 1→1×, 2→2×, 5→½×.

Optionally also renders drool/types.png if matplotlib is available (best-effort; the
Solidity generation never depends on it).
"""

import csv
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
CSV_PATH = REPO / "drool" / "types.csv"
SOL_PATH = REPO / "src" / "types" / "TypeCalcLib.sol"


def multiplier_to_bits(m: int) -> str:
    return {0: "00", 1: "01", 2: "10", 5: "11"}[m]


def parse_csv(csv_file_path: Path):
    """Return (ordered_attacker_names, list_of_2bit_strings_in_index_order)."""
    attackers: list[str] = []
    bits: list[str] = []
    with open(csv_file_path, "r") as f:
        reader = csv.reader(f)
        next(reader)  # header
        for row in reader:
            if not row or all(cell.strip() == "" for cell in row):
                continue
            attacker, defender, multiplier = (c.strip() for c in row)
            if attacker not in attackers:
                attackers.append(attacker)
            bits.append(multiplier_to_bits(int(multiplier)))
    return attackers, bits


def pack(bits: list[str]) -> tuple[int, int]:
    """Pack 2-bit entries into two uint256. Entry i lives at index i; the first 128
    entries go in word 1 (shift i*2), the rest in word 2 (shift (i-128)*2). Each new
    value is prepended so right-shifts extract it later."""
    v1 = ""
    v2 = ""
    for i, b in enumerate(bits):
        if i < 128:
            v1 = b + v1
        else:
            v2 = b + v2
    return int(v1 or "0", 2), int(v2 or "0", 2)


def generate_solidity(num_types: int, m1: int, m2: int) -> str:
    return f"""// SPDX-License-Identifier: AGPL-3.0
pragma solidity ^0.8.0;

import "../Enums.sol";

// Auto-generated by processing/buildTypeChart.py from drool/types.csv — do not edit by hand.
library TypeCalcLib {{
    uint256 private constant MULTIPLIERS_1 = {m1};
    uint256 private constant MULTIPLIERS_2 = {m2};

    function getTypeEffectiveness(Type attackerType, Type defenderType, uint32 basePower)
        internal
        pure
        returns (uint32)
    {{
        uint256 index = uint256(attackerType) * {num_types} + uint256(defenderType);
        uint256 shift;
        uint256 multipliers;

        if (index < 128) {{
            shift = index * 2;
            multipliers = MULTIPLIERS_1;
        }} else {{
            shift = (index - 128) * 2;
            multipliers = MULTIPLIERS_2;
        }}

        uint256 typeEffectivenessValue = uint32((multipliers >> shift) & 3);

        if (typeEffectivenessValue == 0) {{
            return 0;
        }} else if (typeEffectivenessValue == 1) {{
            return basePower;
        }} else if (typeEffectivenessValue == 2) {{
            return basePower * 2;
        }} else {{
            return basePower / 2;
        }}
    }}
}}
"""


def maybe_render_chart(csv_file_path: Path) -> None:
    """Best-effort types.png; skipped silently if matplotlib/numpy are absent."""
    try:
        import numpy as np
        import matplotlib.pyplot as plt
        from matplotlib.colors import LinearSegmentedColormap
    except Exception:
        return

    data, types = {}, []
    with open(csv_file_path) as f:
        reader = csv.reader(f)
        next(reader)
        for row in reader:
            if not row or all(c.strip() == "" for c in row):
                continue
            a, d, m = (c.strip() for c in row)
            if a not in types:
                types.append(a)
            data.setdefault(a, {})[d] = float(m)

    n = len(types)
    matrix = np.ones((n, n))
    for i, a in enumerate(types):
        for j, d in enumerate(types):
            v = data.get(a, {}).get(d, 1)
            matrix[i, j] = 0.5 if v == 5 else (0 if v == 0 else v)

    cmap = LinearSegmentedColormap.from_list("custom", ["#FF4136", "#FFFFFF", "#2ECC40"], N=256)
    fig, ax = plt.subplots(figsize=(15, 15), dpi=200)
    ax.imshow(matrix, cmap=cmap, vmin=0, vmax=2)
    ax.set_xticks(range(n)); ax.set_yticks(range(n))
    ax.set_xticklabels([t.upper() for t in types], rotation=45, ha="right", fontsize=9)
    ax.set_yticklabels([t.upper() for t in types], fontsize=9)
    ax.set_title("Type Effectiveness Chart", fontsize=18, pad=20)
    fig.tight_layout()
    plt.savefig(REPO / "drool" / "types.png", bbox_inches="tight")
    plt.close()


def run() -> bool:
    if not CSV_PATH.exists():
        print(f"Error: missing {CSV_PATH}")
        return False
    attackers, bits = parse_csv(CSV_PATH)
    num_types = len(attackers)
    if len(bits) != num_types * num_types:
        print(f"Error: {len(bits)} entries is not a square ({num_types} types²={num_types**2})")
        return False
    if num_types * num_types > 256:
        print(f"Error: {num_types} types overflow two uint256 words (>256 entries)")
        return False
    m1, m2 = pack(bits)
    SOL_PATH.write_text(generate_solidity(num_types, m1, m2))
    print(f"✅ Wrote {SOL_PATH} ({num_types} types, {len(bits)} entries)")
    maybe_render_chart(CSV_PATH)
    return True


def main():
    import sys
    if not run():
        sys.exit(1)


if __name__ == "__main__":
    main()
