#!/usr/bin/env python3
"""Generate munch's TYPE_EFFECTIVENESS_CHART from drool/types.csv.

drool/types.csv is the single source of truth for type effectiveness (the same file
buildTypeChart.py packs into Solidity). Emits a generated TypeScript module keyed by the
`Type` enum; munch's data/types.ts re-exports it. CSV multipliers map 0→0, 1→1, 2→2, 5→0.5.
Falls back to writing into drool/ when munch isn't checked out.
"""

import csv
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
CSV_PATH = REPO / "drool" / "types.csv"


def convert(value: int):
    return 0.5 if value == 5 else value  # 0, 1, 2 unchanged


def parse(csv_path: Path):
    attackers: list[str] = []
    chart: dict[str, dict[str, float]] = {}
    with open(csv_path) as f:
        reader = csv.reader(f)
        next(reader)  # header
        for row in reader:
            if not row or all(c.strip() == "" for c in row):
                continue
            a, d, m = (c.strip() for c in row)
            if a not in attackers:
                attackers.append(a)
            chart.setdefault(a, {})[d] = convert(int(m))
    return attackers, chart


def fmt(v: float) -> str:
    return str(int(v)) if v == int(v) else str(v)


def generate_ts(attackers: list[str], chart: dict) -> str:
    lines = []
    for a in attackers:
        inner = ",\n".join(
            f"    [Type.{d}]: {fmt(chart[a][d])}" for d in attackers
        )
        lines.append(f"  [Type.{a}]: {{\n{inner}\n  }}")
    body = ",\n".join(lines)
    return f"""// Auto-generated by processing/generate_type_chart.py from drool/types.csv — do not edit.
import {{ Type }} from './sim/Enums';

export type EffectivenessValue = 0 | 0.5 | 1 | 2;

// Real types only (excludes the Type.None single-type sentinel).
type RealType = Exclude<Type, Type.None>;

export const TYPE_EFFECTIVENESS_CHART: {{ [A in RealType]: {{ [D in RealType]: EffectivenessValue }} }} = {{
{body}
}} as const;
"""


def _output_path() -> Path:
    munch_generated = REPO.parent / "munch" / "src" / "app" / "generated"
    if (REPO.parent / "munch" / "src" / "app" / "data").exists():
        return munch_generated / "type-chart.ts"
    return REPO / "drool" / "type-chart.ts"


def run() -> bool:
    if not CSV_PATH.exists():
        print(f"Error: missing {CSV_PATH}")
        return False
    attackers, chart = parse(CSV_PATH)
    out = _output_path()
    out.write_text(generate_ts(attackers, chart), encoding="utf-8")
    print(f"✅ Wrote {out} ({len(attackers)} types)")
    return True


def main():
    if not run():
        sys.exit(1)


if __name__ == "__main__":
    main()
