#!/usr/bin/env python3
"""
Generate generated/eventLayouts.ts for munch and belch from the GachaEvent packing
constants in src/game-layer/GachaTeamRegistry.sol (the single source of truth for the
packed-event bit layout). Eliminates the hand-maintained BONUS_* / bit-offset mirrors
that previously lived in 3 places.

Extracts every `uint256 internal constant (GE_* | BONUS_*)` declaration, evaluates its
(simple) integer expression, and emits the resolved values as plain TS number constants.
"""

import re
import sys
from pathlib import Path

SOL_REL = "src/game-layer/GachaTeamRegistry.sol"
# (consumer repo root, generated dir relative to it)
TARGETS = [
    ("munch", "src/app/generated"),
    ("belch", "src/generated"),
]

CONST_RE = re.compile(
    r"uint256\s+internal\s+constant\s+(GE_[A-Z0-9_]+|BONUS_[A-Z0-9_]+)\s*=\s*([^;]+);"
)


def extract_constants(sol_text: str) -> list[tuple[str, int, str]]:
    """Return [(name, value, source_expr)] in declaration order.

    Expressions are evaluated with already-resolved constants in scope, so
    forms like `(1 << GE_EXP_BITS_PER_MON) - 1` resolve against earlier entries.
    Solidity `<<`, `-`, `()`, and integer literals share Python's syntax.
    """
    scope: dict[str, int] = {}
    out: list[tuple[str, int, str]] = []
    for name, raw in CONST_RE.findall(sol_text):
        expr = raw.strip()
        try:
            value = int(eval(expr, {"__builtins__": {}}, scope))  # noqa: S307 - trusted source
        except Exception as e:  # pragma: no cover
            print(f"  ERROR evaluating {name} = {expr}: {e}")
            sys.exit(1)
        scope[name] = value
        out.append((name, value, expr))
    return out


def render_ts(constants: list[tuple[str, int, str]]) -> str:
    lines = [
        "// DO NOT EDIT — generated by processing/generateEventLayouts.py",
        "// Source of truth: GachaTeamRegistry.sol GachaEvent packing constants.",
        "",
    ]
    for name, value, expr in constants:
        # Show the source expression when it isn't just the literal value.
        suffix = "" if expr == str(value) else f"  // {expr}"
        lines.append(f"export const {name} = {value};{suffix}")
    lines.append("")
    return "\n".join(lines)


def main() -> bool:
    chomp_dir = Path(__file__).parent.parent
    game_dir = chomp_dir.parent
    sol_path = chomp_dir / SOL_REL
    if not sol_path.exists():
        print(f"Error: {sol_path} not found")
        return False

    constants = extract_constants(sol_path.read_text())
    if not constants:
        print("Error: no GE_*/BONUS_* constants found")
        return False
    print(f"Extracted {len(constants)} GachaEvent layout constants")

    ts = render_ts(constants)
    for repo, gen_rel in TARGETS:
        gen_dir = game_dir / repo / gen_rel
        if not gen_dir.exists():
            print(f"  Skipped {repo}: {gen_dir} not found")
            continue
        out_path = gen_dir / "eventLayouts.ts"
        out_path.write_text(ts)
        print(f"  Wrote {out_path}")
    return True


if __name__ == "__main__":
    sys.exit(0 if main() else 1)
