#!/usr/bin/env python3
"""
Generate chomp/script/SetupCPU.s.sol and munch/src/app/data/cpu-teams.ts
from chomp/script/cpu-teams.json (the source of truth).

Mon names are looked up from chomp/drool/mons.csv at generation time, so
the .sol comments and the munch TS file always reflect current naming.
"""

import csv
import json
import sys
from pathlib import Path
from typing import Any


def chomp_dir() -> Path:
    return Path(__file__).parent.parent


def load_mon_names(csv_path: Path) -> dict[int, str]:
    names: dict[int, str] = {}
    with open(csv_path, "r", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            names[int(row["Id"])] = row["Name"]
    return names


def load_cpu_teams(json_path: Path) -> dict[str, Any]:
    with open(json_path, "r", encoding="utf-8") as f:
        return json.load(f)


def render_solidity(data: dict[str, Any], mon_names: dict[int, str]) -> str:
    cpu_players: list[str] = data["cpuPlayers"]
    teams: list[list[int]] = data["teams"]

    lines: list[str] = []
    lines.append("// SPDX-License-Identifier: AGPL-3.0")
    lines.append("// AUTO-GENERATED by processing/generateSetupCPU.py. Do not edit by hand.")
    lines.append("// Source: script/cpu-teams.json")
    lines.append("pragma solidity ^0.8.0;")
    lines.append("")
    lines.append('import "forge-std/Script.sol";')
    lines.append("")
    lines.append('import {GachaTeamRegistry} from "../src/game-layer/GachaTeamRegistry.sol";')
    lines.append("")
    lines.append("struct DeployData {")
    lines.append("    string name;")
    lines.append("    address contractAddress;")
    lines.append("}")
    lines.append("")
    lines.append("contract SetupCPU is Script {")
    lines.append("    DeployData[] deployedContracts;")
    lines.append("")
    lines.append("    function run() external returns (DeployData[] memory) {")
    lines.append("        vm.startBroadcast();")
    lines.append("")
    lines.append('        GachaTeamRegistry gachaTeamRegistry = GachaTeamRegistry(vm.envAddress("GACHA_TEAM_REGISTRY"));')

    lines.append(f"        string[] memory cpuPlayers = new string[]({len(cpu_players)});")
    for i, name in enumerate(cpu_players):
        lines.append(f'        cpuPlayers[{i}] = "{name}";')
    lines.append("")

    team_size = len(teams[0]) if teams else 0
    lines.append(f"        uint256[] memory monIndices = new uint256[]({team_size});")
    lines.append(f"        uint8[] memory facetIds = new uint8[]({team_size});")

    for team_idx, team in enumerate(teams):
        if team_idx > 0:
            lines.append("")
        for slot, mon_id in enumerate(team):
            mon_name = mon_names.get(mon_id, f"mon{mon_id}")
            lines.append(f"        monIndices[{slot}] = {mon_id}; // {mon_name}")
        lines.append("        for (uint256 i; i < cpuPlayers.length; i++) {")
        lines.append(f"            gachaTeamRegistry.setTeamForUser(vm.envAddress(cpuPlayers[i]), {team_idx}, monIndices, facetIds);")
        lines.append("        }")

    lines.append("")
    lines.append("        address[] memory empty = new address[](0);")
    lines.append("        address[] memory cpuAddresses = new address[](cpuPlayers.length);")
    lines.append("        for (uint256 i; i < cpuPlayers.length; i++) {")
    lines.append("            cpuAddresses[i] = vm.envAddress(cpuPlayers[i]);")
    lines.append("        }")
    lines.append("        gachaTeamRegistry.setWhitelistedOpponents(cpuAddresses, empty);")

    lines.append("")
    lines.append("        vm.stopBroadcast();")
    lines.append("")
    lines.append("        return deployedContracts;")
    lines.append("    }")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def render_munch_ts(data: dict[str, Any], mon_names: dict[int, str]) -> str:
    teams: list[list[int]] = data["teams"]

    lines: list[str] = []
    lines.append("// AUTO-GENERATED by chomp/processing/generateSetupCPU.py. Do not edit by hand.")
    lines.append("// Source: chomp/script/cpu-teams.json")
    lines.append("")
    lines.append("export const CPU_TEAMS: readonly (readonly number[])[] = [")
    for team in teams:
        names = ", ".join(mon_names.get(mid, f"mon{mid}") for mid in team)
        indices = ", ".join(str(mid) for mid in team)
        lines.append(f"  [{indices}], // {names}")
    lines.append("] as const;")
    lines.append("")
    return "\n".join(lines)


def run() -> bool:
    base = chomp_dir()
    json_path = base / "script" / "cpu-teams.json"
    sol_path = base / "script" / "SetupCPU.s.sol"
    mons_csv = base / "drool" / "mons.csv"

    if not json_path.exists():
        print(f"ERROR: {json_path} not found", file=sys.stderr)
        return False
    if not mons_csv.exists():
        print(f"ERROR: {mons_csv} not found", file=sys.stderr)
        return False

    data = load_cpu_teams(json_path)
    mon_names = load_mon_names(mons_csv)

    with open(sol_path, "w", encoding="utf-8") as f:
        f.write(render_solidity(data, mon_names))
    print(f"Wrote {sol_path}")

    # Generated artifacts are quarantined under generated/; data/ is the "munch present" guard.
    munch_data = base.parent / "munch" / "src" / "app" / "data"
    munch_generated = base.parent / "munch" / "src" / "app" / "generated"
    if munch_data.exists():
        ts_path = munch_generated / "cpu-teams.ts"
        with open(ts_path, "w", encoding="utf-8") as f:
            f.write(render_munch_ts(data, mon_names))
        print(f"Wrote {ts_path}")
    else:
        print(f"Skipped munch TS: {munch_data} not found")

    return True


if __name__ == "__main__":
    sys.exit(0 if run() else 1)
