#!/usr/bin/env python3
"""
Generate generated/eip712Meta.ts for munch and belch from the EIP-712 sources in the
contracts: the canonical typehash strings (SignedCommitLib.sol) and the per-contract
EIP-712 domain name/version. These were previously hand-mirrored in munch's wallet.ts
and belch's offerSigVerify.ts.

(BattleOffer/Battle EIP-712 types are NOT emitted here — both repos derive those from the
generated SignedMatchmaker ABI via abiComponentsToEip712Types, so the ABI is their source.)
"""

import re
import sys
from pathlib import Path

# Files to scan for `keccak256("StructName(...)")` typehash string literals.
TYPEHASH_SOURCES = ["src/commit-manager/SignedCommitLib.sol"]
# Typehashes whose canonical EIP-712 string lives in a comment because the constant itself is a
# precomputed hex value (the keccak256("...") regex can't reach it). Struct name → source file.
# Battle / BattleOffer are intentionally NOT here — clients derive those from the SignedMatchmaker
# ABI (see the module docstring).
COMMENT_TYPEHASHES = {
    "DualSignedSlotReveal": "src/commit-manager/SignedCommitLib.sol",
    "SeatFill": "src/matchmaker/BattleOfferLib.sol",
}
# Files to scan for an EIP-712 domain (adjacent `name = "..."; version = "...";`).
DOMAIN_SOURCES = [
    "src/Engine.sol",
    "src/matchmaker/SignedMatchmaker.sol",
    "src/commit-manager/SignedCommitManager.sol",
]
TARGETS = [("munch", "src/app/generated"), ("belch", "src/generated")]

TYPEHASH_RE = re.compile(r'keccak256\(\s*"([A-Za-z][A-Za-z0-9]*\([^"]*)"\s*\)')
DOMAIN_RE = re.compile(r'name\s*=\s*"([^"]+)"\s*;\s*\n\s*version\s*=\s*"([^"]+)"\s*;')


def screaming_snake(name: str) -> str:
    return re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", name).upper()


def collect_typehashes(chomp_dir: Path) -> list[tuple[str, str]]:
    """[(STRUCT_NAME_SCREAMING, typehash_string)] deduped, in first-seen order."""
    seen: dict[str, str] = {}
    for rel in TYPEHASH_SOURCES:
        for s in TYPEHASH_RE.findall((chomp_dir / rel).read_text()):
            struct_name = s.split("(", 1)[0]
            seen.setdefault(struct_name, s)
    return [(screaming_snake(n), s) for n, s in seen.items()]


def collect_comment_typehashes(chomp_dir: Path) -> list[tuple[str, str]]:
    """[(STRUCT_NAME_SCREAMING, typehash_string)] for hex-constant typehashes whose canonical
    string is documented in a comment. Matched as `StructName(...)`, which only appears in the
    doc comment (function decls read `hashStructName(` — no word boundary before the struct)."""
    out: list[tuple[str, str]] = []
    for struct_name, rel in COMMENT_TYPEHASHES.items():
        text = (chomp_dir / rel).read_text()
        m = re.search(rf"\b{re.escape(struct_name)}\([^)]*\)", text)
        if not m:
            raise ValueError(f"typehash string for {struct_name} not found in {rel}")
        out.append((screaming_snake(struct_name), m.group(0)))
    return out


def collect_domains(chomp_dir: Path) -> list[tuple[str, str, str]]:
    """[(SCREAMING_NAME, name, version)] — one domain per source contract."""
    out: list[tuple[str, str, str]] = []
    for rel in DOMAIN_SOURCES:
        m = DOMAIN_RE.search((chomp_dir / rel).read_text())
        if m:
            name, version = m.group(1), m.group(2)
            out.append((screaming_snake(name), name, version))
    return out


def render_ts(typehashes: list[tuple[str, str]], domains: list[tuple[str, str, str]]) -> str:
    lines = [
        "// DO NOT EDIT — generated by processing/generateEip712Meta.py",
        "// Source: contract typehash strings + EIP-712 domains.",
        "",
        "// Canonical EIP-712 typehash strings (parse with parseTypehashToEip712Types).",
    ]
    for name, value in typehashes:
        lines.append(f"export const {name}_TYPEHASH = '{value}';")
    lines.append("")
    lines.append("// EIP-712 domain name/version per contract (add chainId + verifyingContract at use).")
    for screaming, name, version in domains:
        lines.append(
            f"export const {screaming}_DOMAIN = {{ name: '{name}', version: '{version}' }} as const;"
        )
    lines.append("")
    return "\n".join(lines)


def main() -> bool:
    chomp_dir = Path(__file__).parent.parent
    game_dir = chomp_dir.parent
    typehashes = collect_typehashes(chomp_dir) + collect_comment_typehashes(chomp_dir)
    domains = collect_domains(chomp_dir)
    if not typehashes or not domains:
        print(f"Error: extracted {len(typehashes)} typehashes, {len(domains)} domains")
        return False
    print(f"Extracted {len(typehashes)} typehash strings, {len(domains)} domains")

    ts = render_ts(typehashes, domains)
    for repo, gen_rel in TARGETS:
        gen_dir = game_dir / repo / gen_rel
        if not gen_dir.exists():
            print(f"  Skipped {repo}: {gen_dir} not found")
            continue
        out_path = gen_dir / "eip712Meta.ts"
        out_path.write_text(ts)
        print(f"  Wrote {out_path}")
    return True


if __name__ == "__main__":
    sys.exit(0 if main() else 1)
