#!/usr/bin/env python3
"""Generate munch's type display metadata (`typeData`) from drool/type-metadata.csv.

drool/type-metadata.csv is the single source of truth for per-type display fields
(name, kanji, colors, emoji, abbreviation). Emits a generated TypeScript module keyed
by the `Type` enum; munch's data/types.ts re-exports it. Falls back to writing into
drool/ when munch isn't checked out.
"""

import csv
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
CSV_PATH = REPO / "drool" / "type-metadata.csv"


def _esc(s: str) -> str:
    return s.replace("\\", "\\\\").replace("'", "\\'")


def generate_ts(rows: list[dict]) -> str:
    entries = []
    for r in rows:
        entries.append(
            f"  [Type.{r['Type']}]: {{ "
            f"bgColor: '{_esc(r['BgColor'])}', "
            f"textColor: '{_esc(r['TextColor'])}', "
            f"abbreviation: '{_esc(r['Abbreviation'])}', "
            f"emoji: '{_esc(r['Emoji'])}', "
            f"name: '{_esc(r['Name'])}', "
            f"character: '{_esc(r['Character'])}' }},"
        )
    body = "\n".join(entries)
    return f"""// Auto-generated by processing/generateTypeMetadata.py from drool/type-metadata.csv — do not edit.
import {{ Type }} from './sim/Enums';

export interface TypeInfo {{
  bgColor: string;
  textColor: string;
  abbreviation: string;
  emoji: string;
  name: string;
  character: string;
}}

// Real types only (excludes the Type.None single-type sentinel).
type RealType = Exclude<Type, Type.None>;

export const typeData: {{ [key in RealType]: TypeInfo }} = {{
{body}
}} as const;
"""


def _output_path() -> Path:
    munch_generated = REPO.parent / "munch" / "src" / "app" / "generated"
    if (REPO.parent / "munch" / "src" / "app" / "data").exists():
        return munch_generated / "type-metadata.ts"
    return REPO / "drool" / "type-metadata.ts"


def run() -> bool:
    if not CSV_PATH.exists():
        print(f"Error: missing {CSV_PATH}")
        return False
    with open(CSV_PATH, encoding="utf-8") as f:
        rows = list(csv.DictReader(f))
    out = _output_path()
    out.write_text(generate_ts(rows), encoding="utf-8")
    print(f"✅ Wrote {out} ({len(rows)} types)")
    return True


def main():
    if not run():
        sys.exit(1)


if __name__ == "__main__":
    main()
