#!/usr/bin/env python3
"""
Generate chomp/script/SetupCPU.s.sol and munch/src/app/data/cpu-teams.ts
from chomp/script/cpu-teams.json (the source of truth).

Mon names and stats are looked up from chomp/drool/mons.csv at generation time,
so the .sol comments and the munch TS file always reflect current naming, and
facet picks for BetterCPU stay consistent with current stat data.

Facet assignment per CPU:
  - OKAY_CPU: no facets (all zeros).
  - FAIR_CPU: random facet in [1, 12] per slot (deterministic seed for reproducibility).
  - BETTER_CPU: min-max picks based on each mon's stats.
      Offensive mons (max(atk, spAtk) > max(def, spDef)):
        Facet 4 (boost Atk, nerf HP) or 5 (boost Atk, nerf Def), whichever
        nerfs the lower base stat (smaller absolute loss at the same 5% cost).
      Defensive mons (otherwise):
        Facet 8 (boost Def, nerf Atk).
Facet ids correspond to the systematic table in Facets.sol — see _facetDef().
"""

import csv
import json
import random
import sys
from pathlib import Path
from typing import Any

# Facet ids from Facets._facetDef (boost, nerf).
FACET_ATK_NERF_HP = 4
FACET_ATK_NERF_DEF = 5
FACET_DEF_NERF_ATK = 8

# Deterministic seed for FairCPU random facet picks. Bumping this rerolls the
# generated facetIds — keep stable unless you intend to regenerate them.
FAIR_CPU_FACET_SEED = 0xC40FFEE


def chomp_dir() -> Path:
    return Path(__file__).parent.parent


def load_mons_data(csv_path: Path) -> dict[int, dict[str, Any]]:
    mons: dict[int, dict[str, Any]] = {}
    with open(csv_path, "r", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            mon_id = int(row["Id"])
            mons[mon_id] = {
                "name": row["Name"],
                "hp": int(row["HP"]),
                "atk": int(row["Attack"]),
                "def": int(row["Defense"]),
                "spAtk": int(row["SpecialAttack"]),
                "spDef": int(row["SpecialDefense"]),
                "speed": int(row["Speed"]),
            }
    return mons


def load_cpu_teams(json_path: Path) -> dict[str, Any]:
    with open(json_path, "r", encoding="utf-8") as f:
        return json.load(f)


def _is_offensive(stats: dict[str, Any]) -> bool:
    return max(stats["atk"], stats["spAtk"]) > max(stats["def"], stats["spDef"])


def _better_cpu_facet(stats: dict[str, Any]) -> int:
    if _is_offensive(stats):
        # Boost Atk; nerf whichever of HP/Def has the smaller base value
        # (5% of the smaller stat is the smaller absolute loss).
        return FACET_ATK_NERF_HP if stats["hp"] <= stats["def"] else FACET_ATK_NERF_DEF
    return FACET_DEF_NERF_ATK


def compute_facets(
    cpu_name: str,
    team: list[int],
    mons: dict[int, dict[str, Any]],
    rng: random.Random,
) -> list[int]:
    if cpu_name == "BETTER_CPU":
        return [_better_cpu_facet(mons[mid]) for mid in team]
    if cpu_name == "FAIR_CPU":
        return [rng.randint(1, 12) for _ in team]
    return [0] * len(team)


def _facet_comment(cpu_name: str, facet_id: int) -> str:
    if facet_id == 0:
        return ""
    if cpu_name == "BETTER_CPU":
        if facet_id == FACET_ATK_NERF_HP:
            return " // +Atk -HP"
        if facet_id == FACET_ATK_NERF_DEF:
            return " // +Atk -Def"
        if facet_id == FACET_DEF_NERF_ATK:
            return " // +Def -Atk"
    return ""


def render_solidity(data: dict[str, Any], mons: dict[int, dict[str, Any]]) -> str:
    cpu_players: list[str] = data["cpuPlayers"]
    hard_cpus: list[str] = data.get("hardCpus", [])
    teams: list[list[int]] = data["teams"]

    rng = random.Random(FAIR_CPU_FACET_SEED)
    # Precompute facets[cpu_idx][team_idx] -> list[int].
    facets_by_cpu_team: list[list[list[int]]] = [
        [compute_facets(name, team, mons, rng) for team in teams]
        for name in cpu_players
    ]

    lines: list[str] = []
    lines.append("// SPDX-License-Identifier: AGPL-3.0")
    lines.append("// AUTO-GENERATED by processing/generateSetupCPU.py. Do not edit by hand.")
    lines.append("// Source: script/cpu-teams.json")
    lines.append("pragma solidity ^0.8.0;")
    lines.append("")
    lines.append('import "forge-std/Script.sol";')
    lines.append("")
    lines.append('import {GachaTeamRegistry} from "../src/game-layer/GachaTeamRegistry.sol";')
    lines.append("")
    lines.append("struct DeployData {")
    lines.append("    string name;")
    lines.append("    address contractAddress;")
    lines.append("}")
    lines.append("")
    lines.append("contract SetupCPU is Script {")
    lines.append("    DeployData[] deployedContracts;")
    lines.append("")
    lines.append("    function run() external returns (DeployData[] memory) {")
    lines.append("        vm.startBroadcast();")
    lines.append("")
    lines.append('        GachaTeamRegistry gachaTeamRegistry = GachaTeamRegistry(vm.envAddress("GACHA_TEAM_REGISTRY"));')

    lines.append(f"        string[] memory cpuPlayers = new string[]({len(cpu_players)});")
    for i, name in enumerate(cpu_players):
        lines.append(f'        cpuPlayers[{i}] = "{name}";')
    lines.append("")

    team_size = len(teams[0]) if teams else 0
    lines.append(f"        uint256[] memory monIndices = new uint256[]({team_size});")
    lines.append(f"        uint8[] memory facetIds = new uint8[]({team_size});")

    for team_idx, team in enumerate(teams):
        if team_idx > 0:
            lines.append("")
        for slot, mon_id in enumerate(team):
            mon_name = mons.get(mon_id, {}).get("name", f"mon{mon_id}")
            lines.append(f"        monIndices[{slot}] = {mon_id}; // {mon_name}")
        for cpu_idx, cpu_name in enumerate(cpu_players):
            facets = facets_by_cpu_team[cpu_idx][team_idx]
            lines.append(f"        // {cpu_name}")
            for slot, fid in enumerate(facets):
                comment = _facet_comment(cpu_name, fid)
                lines.append(f"        facetIds[{slot}] = {fid};{comment}")
            lines.append(
                f'        gachaTeamRegistry.setTeamForUser(vm.envAddress("{cpu_name}"), {team_idx}, monIndices, facetIds);'
            )

    lines.append("")
    lines.append("        address[] memory empty = new address[](0);")
    lines.append("        address[] memory cpuAddresses = new address[](cpuPlayers.length);")
    lines.append("        for (uint256 i; i < cpuPlayers.length; i++) {")
    lines.append("            cpuAddresses[i] = vm.envAddress(cpuPlayers[i]);")
    lines.append("        }")
    lines.append("        gachaTeamRegistry.setWhitelistedOpponents(cpuAddresses, empty);")

    if hard_cpus:
        lines.append("")
        lines.append(f"        address[] memory hardCpus = new address[]({len(hard_cpus)});")
        for i, name in enumerate(hard_cpus):
            lines.append(f'        hardCpus[{i}] = vm.envAddress("{name}");')
        lines.append("        gachaTeamRegistry.setHardCpuOpponents(hardCpus, empty);")

    lines.append("")
    lines.append("        vm.stopBroadcast();")
    lines.append("")
    lines.append("        return deployedContracts;")
    lines.append("    }")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def render_munch_ts(data: dict[str, Any], mons: dict[int, dict[str, Any]]) -> str:
    teams: list[list[int]] = data["teams"]

    lines: list[str] = []
    lines.append("// AUTO-GENERATED by chomp/processing/generateSetupCPU.py. Do not edit by hand.")
    lines.append("// Source: chomp/script/cpu-teams.json")
    lines.append("")
    lines.append("export const CPU_TEAMS: readonly (readonly number[])[] = [")
    for team in teams:
        names = ", ".join(mons.get(mid, {}).get("name", f"mon{mid}") for mid in team)
        indices = ", ".join(str(mid) for mid in team)
        lines.append(f"  [{indices}], // {names}")
    lines.append("] as const;")
    lines.append("")
    return "\n".join(lines)


def run() -> bool:
    base = chomp_dir()
    json_path = base / "script" / "cpu-teams.json"
    sol_path = base / "script" / "SetupCPU.s.sol"
    mons_csv = base / "drool" / "mons.csv"

    if not json_path.exists():
        print(f"ERROR: {json_path} not found", file=sys.stderr)
        return False
    if not mons_csv.exists():
        print(f"ERROR: {mons_csv} not found", file=sys.stderr)
        return False

    data = load_cpu_teams(json_path)
    mons = load_mons_data(mons_csv)

    with open(sol_path, "w", encoding="utf-8") as f:
        f.write(render_solidity(data, mons))
    print(f"Wrote {sol_path}")

    munch_data = base.parent / "munch" / "src" / "app" / "data"
    if munch_data.exists():
        ts_path = munch_data / "cpu-teams.ts"
        with open(ts_path, "w", encoding="utf-8") as f:
            f.write(render_munch_ts(data, mons))
        print(f"Wrote {ts_path}")
    else:
        print(f"Skipped munch TS: {munch_data} not found")

    return True


if __name__ == "__main__":
    sys.exit(0 if run() else 1)
