// SPDX-License-Identifier: AGPL-3.0
pragma solidity ^0.8.0;

import "../Enums.sol";

// Auto-generated by processing/buildTypeChart.py from drool/types.csv — do not edit by hand.
library TypeCalcLib {
    uint256 private constant MULTIPLIERS_1 =
        75716198549227936736822982812955249159801631152768380745492221486153227130200;
    uint256 private constant MULTIPLIERS_2 = 35843740606796099032740410262627249642837;

    function getTypeEffectiveness(Type attackerType, Type defenderType, uint32 basePower)
        internal
        pure
        returns (uint32)
    {
        uint256 index = uint256(attackerType) * 14 + uint256(defenderType);
        uint256 shift;
        uint256 multipliers;

        if (index < 128) {
            shift = index * 2;
            multipliers = MULTIPLIERS_1;
        } else {
            shift = (index - 128) * 2;
            multipliers = MULTIPLIERS_2;
        }

        uint256 typeEffectivenessValue = uint32((multipliers >> shift) & 3);

        if (typeEffectivenessValue == 0) {
            return 0;
        } else if (typeEffectivenessValue == 1) {
            return basePower;
        } else if (typeEffectivenessValue == 2) {
            return basePower * 2;
        } else {
            return basePower / 2;
        }
    }
}
