// Auto-generated by sol2ts transpiler
// Do not edit manually

import { keccak256, encodePacked, encodeAbiParameters, parseAbiParameters } from 'viem';

export class AttackCalculator {
  // Storage
  protected _storage: Map<string, any> = new Map();
  protected _transient: Map<string, any> = new Map();

  static readonly RNG_SCALING_DENOM: bigint = BigInt(100);
  protected _calculateDamage(ENGINE: IEngine, TYPE_CALCULATOR: ITypeCalculator, battleKey: string, attackerPlayerIndex: bigint, basePower: bigint, accuracy: bigint, volatility: bigint, attackType: Type, attackSupertype: MoveClass, rng: bigint, critRate: bigint): [bigint, string] {
    let defenderPlayerIndex: bigint = ((((attackerPlayerIndex) + (BigInt(1)))) % (BigInt(2)));
    let ctx: DamageCalcContext = ENGINE.getDamageCalcContext(battleKey, attackerPlayerIndex, defenderPlayerIndex);
    const [damage, eventType] = _calculateDamageFromContext(TYPE_CALCULATOR, ctx, basePower, accuracy, volatility, attackType, attackSupertype, rng, critRate);
    if (((damage) != (BigInt(0)))) {
      ENGINE.dealDamage(defenderPlayerIndex, ctx.defenderMonIndex, damage);
    }
    if (((eventType) != ((BigInt(0))))) {
      ENGINE.emitEngineEvent(eventType, "");
    }
    return [damage, eventType];
  }

  protected _calculateDamageView(ENGINE: IEngine, TYPE_CALCULATOR: ITypeCalculator, battleKey: string, attackerPlayerIndex: bigint, defenderPlayerIndex: bigint, basePower: bigint, accuracy: bigint, volatility: bigint, attackType: Type, attackSupertype: MoveClass, rng: bigint, critRate: bigint): [bigint, string] {
    let ctx: DamageCalcContext = ENGINE.getDamageCalcContext(battleKey, attackerPlayerIndex, defenderPlayerIndex);
    return _calculateDamageFromContext(TYPE_CALCULATOR, ctx, basePower, accuracy, volatility, attackType, attackSupertype, rng, critRate);
  }

  protected _calculateDamageFromContext(TYPE_CALCULATOR: ITypeCalculator, ctx: DamageCalcContext, basePower: bigint, accuracy: bigint, volatility: bigint, attackType: Type, attackSupertype: MoveClass, rng: bigint, critRate: bigint): [bigint, string] {
    if (((((rng) % (BigInt(100)))) >= (accuracy))) {
      return [BigInt(0), MOVE_MISS_EVENT_TYPE];
    }
    let damage: bigint;
    let eventType: string = NONE_EVENT_TYPE;
    {
      let attackStat: bigint;
      let defenceStat: bigint;
      if (((attackSupertype) == (MoveClass.Physical))) {
        ((attackStat) = ((BigInt(((BigInt(ctx.attackerAttack)) + (ctx.attackerAttackDelta))) & BigInt(4294967295))));
        ((defenceStat) = ((BigInt(((BigInt(ctx.defenderDef)) + (ctx.defenderDefDelta))) & BigInt(4294967295))));
      }
      else {
        ((attackStat) = ((BigInt(((BigInt(ctx.attackerSpAtk)) + (ctx.attackerSpAtkDelta))) & BigInt(4294967295))));
        ((defenceStat) = ((BigInt(((BigInt(ctx.defenderSpDef)) + (ctx.defenderSpDefDelta))) & BigInt(4294967295))));
      }
      if (((attackStat) <= (BigInt(0)))) {
        ((attackStat) = (BigInt(1)));
      }
      if (((defenceStat) <= (BigInt(0)))) {
        ((defenceStat) = (BigInt(1)));
      }
      let scaledBasePower: bigint;
      {
        ((scaledBasePower) = (TYPE_CALCULATOR.getTypeEffectiveness(attackType, ctx.defenderType1, basePower)));
        if (((ctx.defenderType2) != (Type.None))) {
          ((scaledBasePower) = (TYPE_CALCULATOR.getTypeEffectiveness(attackType, ctx.defenderType2, scaledBasePower)));
        }
      }
      let rng2: bigint = (BigInt(keccak256(encodeAbiParameters(rng))) & BigInt(115792089237316195423570985008687907853269984665640564039457584007913129639935));
      let rngScaling: bigint = BigInt(100);
      if (((volatility) > (BigInt(0)))) {
        if (((((rng2) % (BigInt(100)))) > (BigInt(50)))) {
          ((rngScaling) = (((BigInt(100)) + ((BigInt(((rng2) % (((volatility) + (BigInt(1)))))) & BigInt(4294967295))))));
        }
        else {
          ((rngScaling) = (((BigInt(100)) - ((BigInt(((rng2) % (((volatility) + (BigInt(1)))))) & BigInt(4294967295))))));
        }
      }
      let rng3: bigint = (BigInt(keccak256(encodeAbiParameters(rng2))) & BigInt(115792089237316195423570985008687907853269984665640564039457584007913129639935));
      let critNum: bigint = BigInt(1);
      let critDenom: bigint = BigInt(1);
      if (((((rng3) % (BigInt(100)))) <= (critRate))) {
        ((critNum) = (CRIT_NUM));
        ((critDenom) = (CRIT_DENOM));
        ((eventType) = (MOVE_CRIT_EVENT_TYPE));
      }
      ((damage) = (BigInt(((((critNum) * (((((scaledBasePower) * (attackStat))) * (rngScaling))))) / (((((defenceStat) * (RNG_SCALING_DENOM))) * (critDenom)))))));
      if (((scaledBasePower) == (BigInt(0)))) {
        ((eventType) = (MOVE_TYPE_IMMUNITY_EVENT_TYPE));
      }
    }
    return [damage, eventType];
  }

}
