// Auto-generated by sol2ts transpiler
// Do not edit manually

import { keccak256, encodePacked, encodeAbiParameters, parseAbiParameters } from 'viem';

export abstract class BasicEffect extends IEffect {
  // Storage
  protected _storage: Map<string, any> = new Map();
  protected _transient: Map<string, any> = new Map();

  name(): string {
    return "";
  }

  shouldRunAtStep(r: EffectStep): boolean {
  }

  shouldApply(_arg0: string, _arg1: bigint, _arg2: bigint): boolean {
    return true;
  }

  onRoundStart(_arg0: bigint, extraData: string, _arg2: bigint, _arg3: bigint): [string, boolean] {
    return [extraData, false];
  }

  onRoundEnd(_arg0: bigint, extraData: string, _arg2: bigint, _arg3: bigint): [string, boolean] {
    return [extraData, false];
  }

  onMonSwitchIn(_arg0: bigint, extraData: string, _arg2: bigint, _arg3: bigint): [string, boolean] {
    return [extraData, false];
  }

  onMonSwitchOut(_arg0: bigint, extraData: string, _arg2: bigint, _arg3: bigint): [string, boolean] {
    return [extraData, false];
  }

  onAfterDamage(_arg0: bigint, extraData: string, _arg2: bigint, _arg3: bigint, _arg4: bigint): [string, boolean] {
    return [extraData, false];
  }

  onAfterMove(_arg0: bigint, extraData: string, _arg2: bigint, _arg3: bigint): [string, boolean] {
    return [extraData, false];
  }

  onUpdateMonState(_arg0: bigint, extraData: string, _arg2: bigint, _arg3: bigint, _arg4: MonStateIndexName, _arg5: bigint): [string, boolean] {
    return [extraData, false];
  }

  onApply(_arg0: bigint, _arg1: string, _arg2: bigint, _arg3: bigint): [string, boolean] {
    return [updatedExtraData, removeAfterRun];
  }

  onRemove(extraData: string, targetIndex: bigint, monIndex: bigint): void {
  }

}
