// Auto-generated by sol2ts transpiler
// Do not edit manually

import { keccak256, encodePacked, encodeAbiParameters, parseAbiParameters } from 'viem';

export const NO_OP_MOVE_INDEX: bigint = BigInt(126);

export const SWITCH_MOVE_INDEX: bigint = BigInt(125);

export const MOVE_INDEX_OFFSET: bigint = BigInt(1);

export const MOVE_INDEX_MASK: bigint = BigInt("0x7F");

export const IS_REAL_TURN_BIT: bigint = BigInt("0x80");

export const SWITCH_PRIORITY: bigint = BigInt(6);

export const DEFAULT_PRIORITY: bigint = BigInt(3);

export const DEFAULT_STAMINA: bigint = BigInt(5);

export const CRIT_NUM: bigint = BigInt(3);

export const CRIT_DENOM: bigint = BigInt(2);

export const DEFAULT_CRIT_RATE: bigint = BigInt(5);

export const DEFAULT_VOL: bigint = BigInt(10);

export const DEFAULT_ACCURACY: bigint = BigInt(100);

export const CLEARED_MON_STATE_SENTINEL: bigint = BigInt("2147483647") - BigInt(1);

export const PACKED_CLEARED_MON_STATE: bigint = BigInt("0x00007FFFFFFE7FFFFFFE7FFFFFFE7FFFFFFE7FFFFFFE7FFFFFFE7FFFFFFE");

export const PLAYER_EFFECT_BITS: bigint = BigInt(6);

export const MAX_EFFECTS_PER_MON: bigint = (BigInt(2) ** PLAYER_EFFECT_BITS) - BigInt(1);

export const EFFECT_SLOTS_PER_MON: bigint = BigInt(64);

export const EFFECT_COUNT_MASK: bigint = BigInt("0x3F");

export const TOMBSTONE_ADDRESS: string = BigInt("0xdead");

export const MAX_BATTLE_DURATION: bigint = BigInt(1) * BigInt(3600);

export const MOVE_MISS_EVENT_TYPE: string = sha256(encodeAbiParameters("MoveMiss"));

export const MOVE_CRIT_EVENT_TYPE: string = sha256(encodeAbiParameters("MoveCrit"));

export const MOVE_TYPE_IMMUNITY_EVENT_TYPE: string = sha256(encodeAbiParameters("MoveTypeImmunity"));

export const NONE_EVENT_TYPE: string = BigInt(0);

