// Auto-generated by sol2ts transpiler
// Do not edit manually

import { keccak256, encodePacked, encodeAbiParameters, parseAbiParameters } from 'viem';

export interface IAbility {
  name(): string;
  activateOnSwitch(battleKey: string, playerIndex: bigint, monIndex: bigint): void;
}

