// Auto-generated by sol2ts transpiler
// Do not edit manually

import { keccak256, encodePacked, encodeAbiParameters, parseAbiParameters } from 'viem';

export interface IEffect {
  name(): string;
  shouldRunAtStep(r: EffectStep): boolean;
  shouldApply(extraData: string, targetIndex: bigint, monIndex: bigint): boolean;
  onRoundStart(rng: bigint, extraData: string, targetIndex: bigint, monIndex: bigint): [string, boolean];
  onRoundEnd(rng: bigint, extraData: string, targetIndex: bigint, monIndex: bigint): [string, boolean];
  onMonSwitchIn(rng: bigint, extraData: string, targetIndex: bigint, monIndex: bigint): [string, boolean];
  onMonSwitchOut(rng: bigint, extraData: string, targetIndex: bigint, monIndex: bigint): [string, boolean];
  onAfterDamage(rng: bigint, extraData: string, targetIndex: bigint, monIndex: bigint, damage: bigint): [string, boolean];
  onAfterMove(rng: bigint, extraData: string, targetIndex: bigint, monIndex: bigint): [string, boolean];
  onUpdateMonState(rng: bigint, extraData: string, playerIndex: bigint, monIndex: bigint, stateVarIndex: MonStateIndexName, valueToAdd: bigint): [string, boolean];
  onApply(rng: bigint, extraData: string, targetIndex: bigint, monIndex: bigint): [string, boolean];
  onRemove(extraData: string, targetIndex: bigint, monIndex: bigint): void;
}

