// Auto-generated by sol2ts transpiler
// Do not edit manually

import { keccak256, encodePacked, encodeAbiParameters, parseAbiParameters } from 'viem';

export interface IEngine {
  battleKeyForWrite(): string;
  tempRNG(): bigint;
  updateMatchmakers(makersToAdd: string[], makersToRemove: string[]): void;
  startBattle(battle: Battle): void;
  updateMonState(playerIndex: bigint, monIndex: bigint, stateVarIndex: MonStateIndexName, valueToAdd: bigint): void;
  addEffect(targetIndex: bigint, monIndex: bigint, effect: IEffect, extraData: string): void;
  removeEffect(targetIndex: bigint, monIndex: bigint, effectIndex: bigint): void;
  editEffect(targetIndex: bigint, monIndex: bigint, effectIndex: bigint, newExtraData: string): void;
  setGlobalKV(key: string, value: bigint): void;
  dealDamage(playerIndex: bigint, monIndex: bigint, damage: bigint): void;
  switchActiveMon(playerIndex: bigint, monToSwitchIndex: bigint): void;
  setMove(battleKey: string, playerIndex: bigint, moveIndex: bigint, salt: string, extraData: bigint): void;
  execute(battleKey: string): void;
  emitEngineEvent(eventType: string, extraData: string): void;
  setUpstreamCaller(caller: string): void;
  computeBattleKey(p0: string, p1: string): [string, string];
  computePriorityPlayerIndex(battleKey: string, rng: bigint): bigint;
  getMoveManager(battleKey: string): string;
  getBattle(battleKey: string): [BattleConfigView, BattleData];
  getMonValueForBattle(battleKey: string, playerIndex: bigint, monIndex: bigint, stateVarIndex: MonStateIndexName): bigint;
  getMonStatsForBattle(battleKey: string, playerIndex: bigint, monIndex: bigint): MonStats;
  getMonStateForBattle(battleKey: string, playerIndex: bigint, monIndex: bigint, stateVarIndex: MonStateIndexName): bigint;
  getMonStateForStorageKey(storageKey: string, playerIndex: bigint, monIndex: bigint, stateVarIndex: MonStateIndexName): bigint;
  getMoveForMonForBattle(battleKey: string, playerIndex: bigint, monIndex: bigint, moveIndex: bigint): IMoveSet;
  getMoveDecisionForBattleState(battleKey: string, playerIndex: bigint): MoveDecision;
  getPlayersForBattle(battleKey: string): string[];
  getTeamSize(battleKey: string, playerIndex: bigint): bigint;
  getTurnIdForBattleState(battleKey: string): bigint;
  getActiveMonIndexForBattleState(battleKey: string): bigint[];
  getPlayerSwitchForTurnFlagForBattleState(battleKey: string): bigint;
  getGlobalKV(battleKey: string, key: string): bigint;
  getBattleValidator(battleKey: string): IValidator;
  getEffects(battleKey: string, targetIndex: bigint, monIndex: bigint): [EffectInstance[], bigint[]];
  getWinner(battleKey: string): string;
  getStartTimestamp(battleKey: string): bigint;
  getPrevPlayerSwitchForTurnFlagForBattleState(battleKey: string): bigint;
  getBattleContext(battleKey: string): BattleContext;
  getCommitContext(battleKey: string): CommitContext;
  getDamageCalcContext(battleKey: string, attackerPlayerIndex: bigint, defenderPlayerIndex: bigint): DamageCalcContext;
}

