// Auto-generated by sol2ts transpiler
// Do not edit manually

import { keccak256, encodePacked, encodeAbiParameters, parseAbiParameters } from 'viem';

export interface IEngineHook {
  onBattleStart(battleKey: string): void;
  onRoundStart(battleKey: string): void;
  onRoundEnd(battleKey: string): void;
  onBattleEnd(battleKey: string): void;
}

