// Auto-generated by sol2ts transpiler
// Do not edit manually

import { keccak256, encodePacked, encodeAbiParameters, parseAbiParameters } from 'viem';

export interface IMoveSet {
  name(): string;
  move(battleKey: string, attackerPlayerIndex: bigint, extraData: bigint, rng: bigint): void;
  priority(battleKey: string, attackerPlayerIndex: bigint): bigint;
  stamina(battleKey: string, attackerPlayerIndex: bigint, monIndex: bigint): bigint;
  moveType(battleKey: string): Type;
  isValidTarget(battleKey: string, extraData: bigint): boolean;
  moveClass(battleKey: string): MoveClass;
  extraDataType(): ExtraDataType;
}

