// Auto-generated by sol2ts transpiler
// Do not edit manually

import { keccak256, encodePacked, encodeAbiParameters, parseAbiParameters } from 'viem';

export interface IRandomnessOracle {
  getRNG(source0: string, source1: string): bigint;
}

