// Auto-generated by sol2ts transpiler
// Do not edit manually

import { keccak256, encodePacked, encodeAbiParameters, parseAbiParameters } from 'viem';

export interface IRuleset {
  getInitialGlobalEffects(): [IEffect[], string[]];
}

