// Auto-generated by sol2ts transpiler
// Do not edit manually

import { keccak256, encodePacked, encodeAbiParameters, parseAbiParameters } from 'viem';

export interface ITeamRegistry {
  getMonRegistry(): IMonRegistry;
  getTeam(player: string, teamIndex: bigint): Mon[];
  getTeams(p0: string, p0TeamIndex: bigint, p1: string, p1TeamIndex: bigint): [Mon[], Mon[]];
  getTeamCount(player: string): bigint;
  getMonRegistryIndicesForTeam(player: string, teamIndex: bigint): bigint[];
}

