// Auto-generated by sol2ts transpiler
// Do not edit manually

import { keccak256, encodePacked, encodeAbiParameters, parseAbiParameters } from 'viem';

export interface IValidator {
  validateGameStart(p0: string, p1: string, teams: Mon[][], teamRegistry: ITeamRegistry, p0TeamIndex: bigint, p1TeamIndex: bigint): boolean;
  validatePlayerMove(battleKey: string, moveIndex: bigint, playerIndex: bigint, extraData: bigint): boolean;
  validateSpecificMoveSelection(battleKey: string, moveIndex: bigint, playerIndex: bigint, extraData: bigint): boolean;
  validateSwitch(battleKey: string, playerIndex: bigint, monToSwitchIndex: bigint): boolean;
  validateTimeout(battleKey: string, presumedAFKPlayerIndex: bigint): string;
}

