// Auto-generated by sol2ts transpiler
// Do not edit manually

import { keccak256, encodePacked, encodeAbiParameters, parseAbiParameters } from 'viem';

export class StandardAttack extends IMoveSet implements Ownable {
  // Storage
  protected _storage: Map<string, any> = new Map();
  protected _transient: Map<string, any> = new Map();

  readonly ENGINE: IEngine = undefined as any;
  readonly TYPE_CALCULATOR: ITypeCalculator = undefined as any;
  private _basePower: bigint = 0n;
  private _stamina: bigint = 0n;
  private _accuracy: bigint = 0n;
  private _priority: bigint = 0n;
  private _moveType: Type = undefined as any;
  private _effectAccuracy: bigint = 0n;
  private _moveClass: MoveClass = undefined as any;
  private _critRate: bigint = 0n;
  private _volatility: bigint = 0n;
  private _effect: IEffect = undefined as any;
  private _name: string = "";
  constructor(owner: string, _ENGINE: IEngine, _TYPE_CALCULATOR: ITypeCalculator, params: ATTACK_PARAMS) {
    ((ENGINE) = (_ENGINE));
    ((TYPE_CALCULATOR) = (_TYPE_CALCULATOR));
    ((_basePower) = (params.BASE_POWER));
    ((_stamina) = (params.STAMINA_COST));
    ((_accuracy) = (params.ACCURACY));
    ((_priority) = (params.PRIORITY));
    ((_moveType) = (params.MOVE_TYPE));
    ((_effectAccuracy) = (params.EFFECT_ACCURACY));
    ((_moveClass) = (params.MOVE_CLASS));
    ((_critRate) = (params.CRIT_RATE));
    ((_volatility) = (params.VOLATILITY));
    ((_effect) = (params.EFFECT));
    ((_name) = (params.NAME));
    _initializeOwner(owner);
  }

  move(battleKey: string, attackerPlayerIndex: bigint, _arg2: bigint, rng: bigint): void {
    _move(battleKey, attackerPlayerIndex, rng);
  }

  protected _move(battleKey: string, attackerPlayerIndex: bigint, rng: bigint): [bigint, string] {
    let damage: bigint = BigInt(0);
    let eventType: string = (BigInt(0));
    if (((basePower(battleKey)) > (BigInt(0)))) {
      (([damage, eventType]) = (AttackCalculator._calculateDamage(ENGINE, TYPE_CALCULATOR, battleKey, attackerPlayerIndex, basePower(battleKey), accuracy(battleKey), volatility(battleKey), moveType(battleKey), moveClass(battleKey), rng, critRate(battleKey))));
    }
    if (((((rng) % (BigInt(100)))) < (_effectAccuracy))) {
      let defenderPlayerIndex: bigint = ((((attackerPlayerIndex) + (BigInt(1)))) % (BigInt(2)));
      let defenderMonIndex: bigint = ENGINE.getActiveMonIndexForBattleState(ENGINE.battleKeyForWrite()).get(defenderPlayerIndex);
      if (((String(_effect)) != (String(BigInt(0))))) {
        ENGINE.addEffect(defenderPlayerIndex, defenderMonIndex, _effect, "");
      }
    }
    return [damage, eventType];
  }

  isValidTarget(_arg0: string, _arg1: bigint): boolean {
    return true;
  }

  priority(_arg0: string, _arg1: bigint): bigint {
    return _priority;
  }

  stamina(_arg0: string, _arg1: bigint, _arg2: bigint): bigint {
    return _stamina;
  }

  moveType(_arg0: string): Type {
    return _moveType;
  }

  moveClass(_arg0: string): MoveClass {
    return _moveClass;
  }

  critRate(_arg0: string): bigint {
    return _critRate;
  }

  volatility(_arg0: string): bigint {
    return _volatility;
  }

  basePower(_arg0: string): bigint {
    return _basePower;
  }

  accuracy(_arg0: string): bigint {
    return _accuracy;
  }

  effect(_arg0: string): IEffect {
    return _effect;
  }

  effectAccuracy(_arg0: string): bigint {
    return _effectAccuracy;
  }

  changeVar(varToChange: bigint, newValue: bigint): void {
    if (((varToChange) == (BigInt(0)))) {
      ((_basePower) = ((BigInt(newValue) & BigInt(4294967295))));
    } else if (((varToChange) == (BigInt(1)))) {
      ((_stamina) = ((BigInt(newValue) & BigInt(4294967295))));
    } else if (((varToChange) == (BigInt(2)))) {
      ((_accuracy) = ((BigInt(newValue) & BigInt(4294967295))));
    } else if (((varToChange) == (BigInt(3)))) {
      ((_priority) = ((BigInt(newValue) & BigInt(4294967295))));
    } else if (((varToChange) == (BigInt(4)))) {
      ((_moveType) = (Type(newValue)));
    } else if (((varToChange) == (BigInt(5)))) {
      ((_effectAccuracy) = ((BigInt(newValue) & BigInt(4294967295))));
    } else if (((varToChange) == (BigInt(6)))) {
      ((_moveClass) = (MoveClass(newValue)));
    } else if (((varToChange) == (BigInt(7)))) {
      ((_critRate) = ((BigInt(newValue) & BigInt(4294967295))));
    } else if (((varToChange) == (BigInt(8)))) {
      ((_volatility) = ((BigInt(newValue) & BigInt(4294967295))));
    } else if (((varToChange) == (BigInt(9)))) {
      ((_effect) = (IEffect(String((BigInt(newValue) & BigInt(1461501637330902918203684832716283019655932542975))))));
    }
  }

  extraDataType(): ExtraDataType {
    return ExtraDataType.None;
  }

  name(): string {
    return _name;
  }

}
