// Auto-generated by sol2ts transpiler
// Do not edit manually

import { keccak256, encodePacked, encodeAbiParameters, parseAbiParameters } from 'viem';

export interface ProposedBattle {
  p0: string;
  p0TeamIndex: bigint;
  p0TeamHash: string;
  p1: string;
  p1TeamIndex: bigint;
  teamRegistry: ITeamRegistry;
  validator: IValidator;
  rngOracle: IRandomnessOracle;
  ruleset: IRuleset;
  moveManager: string;
  matchmaker: IMatchmaker;
  engineHooks: IEngineHook[];
}

export interface Battle {
  p0: string;
  p0TeamIndex: bigint;
  p1: string;
  p1TeamIndex: bigint;
  teamRegistry: ITeamRegistry;
  validator: IValidator;
  rngOracle: IRandomnessOracle;
  ruleset: IRuleset;
  moveManager: string;
  matchmaker: IMatchmaker;
  engineHooks: IEngineHook[];
}

export interface MoveDecision {
  packedMoveIndex: bigint;
  extraData: bigint;
}

export interface BattleData {
  p1: string;
  turnId: bigint;
  p0: string;
  winnerIndex: bigint;
  prevPlayerSwitchForTurnFlag: bigint;
  playerSwitchForTurnFlag: bigint;
  activeMonIndex: bigint;
}

export interface BattleConfig {
  validator: IValidator;
  packedP0EffectsCount: bigint;
  rngOracle: IRandomnessOracle;
  packedP1EffectsCount: bigint;
  moveManager: string;
  globalEffectsLength: bigint;
  teamSizes: bigint;
  engineHooksLength: bigint;
  koBitmaps: bigint;
  startTimestamp: bigint;
  p0Salt: string;
  p1Salt: string;
  p0Move: MoveDecision;
  p1Move: MoveDecision;
  p0Team: Map<bigint, Mon>;
  p1Team: Map<bigint, Mon>;
  p0States: Map<bigint, MonState>;
  p1States: Map<bigint, MonState>;
  globalEffects: Map<bigint, EffectInstance>;
  p0Effects: Map<bigint, EffectInstance>;
  p1Effects: Map<bigint, EffectInstance>;
  engineHooks: Map<bigint, IEngineHook>;
}

export interface EffectInstance {
  effect: IEffect;
  data: string;
}

export interface BattleConfigView {
  validator: IValidator;
  rngOracle: IRandomnessOracle;
  moveManager: string;
  globalEffectsLength: bigint;
  packedP0EffectsCount: bigint;
  packedP1EffectsCount: bigint;
  teamSizes: bigint;
  p0Salt: string;
  p1Salt: string;
  p0Move: MoveDecision;
  p1Move: MoveDecision;
  globalEffects: EffectInstance[];
  p0Effects: EffectInstance[][];
  p1Effects: EffectInstance[][];
  teams: Mon[][];
  monStates: MonState[][];
}

export interface BattleState {
  winnerIndex: bigint;
  prevPlayerSwitchForTurnFlag: bigint;
  playerSwitchForTurnFlag: bigint;
  activeMonIndex: bigint;
  turnId: bigint;
}

export interface MonStats {
  hp: bigint;
  stamina: bigint;
  speed: bigint;
  attack: bigint;
  defense: bigint;
  specialAttack: bigint;
  specialDefense: bigint;
  type1: Type;
  type2: Type;
}

export interface Mon {
  stats: MonStats;
  ability: IAbility;
  moves: IMoveSet[];
}

export interface MonState {
  hpDelta: bigint;
  staminaDelta: bigint;
  speedDelta: bigint;
  attackDelta: bigint;
  defenceDelta: bigint;
  specialAttackDelta: bigint;
  specialDefenceDelta: bigint;
  isKnockedOut: boolean;
  shouldSkipTurn: boolean;
}

export interface PlayerDecisionData {
  numMovesRevealed: bigint;
  lastCommitmentTurnId: bigint;
  lastMoveTimestamp: bigint;
  moveHash: string;
}

export interface RevealedMove {
  moveIndex: bigint;
  extraData: bigint;
  salt: string;
}

export interface StatBoostToApply {
  stat: MonStateIndexName;
  boostPercent: bigint;
  boostType: StatBoostType;
}

export interface StatBoostUpdate {
  stat: MonStateIndexName;
  oldStat: bigint;
  newStat: bigint;
}

export interface BattleContext {
  startTimestamp: bigint;
  p0: string;
  p1: string;
  winnerIndex: bigint;
  turnId: bigint;
  playerSwitchForTurnFlag: bigint;
  prevPlayerSwitchForTurnFlag: bigint;
  p0ActiveMonIndex: bigint;
  p1ActiveMonIndex: bigint;
  validator: string;
  moveManager: string;
}

export interface CommitContext {
  startTimestamp: bigint;
  p0: string;
  p1: string;
  winnerIndex: bigint;
  turnId: bigint;
  playerSwitchForTurnFlag: bigint;
  validator: string;
}

export interface DamageCalcContext {
  attackerMonIndex: bigint;
  defenderMonIndex: bigint;
  attackerAttack: bigint;
  attackerAttackDelta: bigint;
  attackerSpAtk: bigint;
  attackerSpAtkDelta: bigint;
  defenderDef: bigint;
  defenderDefDelta: bigint;
  defenderSpDef: bigint;
  defenderSpDefDelta: bigint;
  defenderType1: Type;
  defenderType2: Type;
}

