"""Per-file Rust code generator (analog of codegen.generator).

One Solidity source file becomes one Rust module file at the mirrored
relative path inside the emitted engine crate. The generator emits the file
body first (collecting cross-module type/constant/trait usage as a side
effect), then prepends the computed ``use`` lines.
"""

from typing import Dict, Optional, Set, Tuple

from ..parser.ast_nodes import SourceUnit
from .context import RustCodeGenerationContext
from .contract import RustContractGenerator
from .definition import RustDefinitionGenerator
from .expression import RustExpressionGenerator
from .function import RustFunctionGenerator
from .rust_types import RustTypeConverter, rust_ident
from .soltypes import TypeInferencer
from .statement import RustStatementGenerator
from .symbols import RustSymbols


HEADER = (
    '// Auto-generated by the sol2rs transpiler backend\n'
    '// Do not edit manually\n'
)

PRELUDE = (
    'use chomp_rt as rt;\n'
    'use chomp_rt::{U256, I256, B256, Address, SolOps, SolShift};\n'
)


class RustCodeGenerator:
    """Generates one Rust module from one Solidity SourceUnit."""

    def __init__(self, symbols: RustSymbols, dyn_interfaces: Set[str],
                 rel_path: str):
        self._symbols = symbols
        self._dyn_interfaces = dyn_interfaces
        self._rel_path = rel_path
        self._module = RustSymbols._module_path(rel_path)

        self._ctx = RustCodeGenerationContext(current_file_path=rel_path)
        self._types = RustTypeConverter(symbols, self._ctx)
        self._infer = TypeInferencer(symbols, self._ctx)
        self._expr = RustExpressionGenerator(self._ctx, symbols, self._types, self._infer)
        self._stmt = RustStatementGenerator(self._ctx, self._expr, self._types, self._infer)
        self._func = RustFunctionGenerator(
            self._ctx, symbols, self._expr, self._stmt, self._types, self._infer,
            dyn_interfaces,
        )
        self._defs = RustDefinitionGenerator(
            self._ctx, symbols, self._types, self._expr, self._infer,
        )
        self._contract = RustContractGenerator(
            self._ctx, symbols, self._types, self._func, self._defs, self._infer,
            dyn_interfaces,
        )

    @property
    def notes(self):
        return self._ctx.notes

    def generate(self, ast: SourceUnit) -> str:
        body_parts = []

        for enum in ast.enums:
            body_parts.append(self._defs.generate_enum(enum))
        for const in ast.constants:
            body_parts.append(self._defs.generate_constant(const))
        for struct in ast.structs:
            body_parts.append(self._defs.generate_struct(struct))
        for contract in ast.contracts:
            self._ctx.reset_for_contract()
            body_parts.append(self._contract.generate_contract(contract))

        body = '\n'.join(body_parts)
        uses = self._use_lines()
        parts = [HEADER, PRELUDE]
        if uses:
            parts.append(uses)
        parts.append('')
        parts.append(body)
        return '\n'.join(parts)

    # ------------------------------------------------------------------

    def _use_lines(self) -> str:
        lines = set()

        def path_of(name: str) -> Optional[Tuple[str, ...]]:
            return self._symbols.module_of.get(name)

        for name in self._ctx.used_types | self._ctx.used_constants:
            mod = path_of(name)
            if mod is None or mod == self._module:
                continue
            lines.add(f'use crate::{"::".join(mod)}::{rust_ident(name)};')

        for name in self._ctx.used_traits:
            mod = path_of(name)
            if mod is None or mod == self._module:
                continue
            lines.add(f'use crate::{"::".join(mod)}::{rust_ident(name)};')

        for name in self._ctx.used_modules:
            mod = path_of(name)
            if mod is None or mod == self._module:
                continue
            if mod[-1] == name:
                lines.add(f'use crate::{"::".join(mod)};')
            else:
                lines.add(f'use crate::{"::".join(mod)} as {rust_ident(name)};')

        return '\n'.join(sorted(lines))
