// SPDX-License-Identifier: AGPL-3.0
// AUTO-GENERATED by processing/generateSetupCPU.py. Do not edit by hand.
// Source: script/cpu-teams.json
pragma solidity ^0.8.0;

import "forge-std/Script.sol";

import {GachaTeamRegistry} from "../src/game-layer/GachaTeamRegistry.sol";

struct DeployData {
    string name;
    address contractAddress;
}

contract SetupCPU is Script {
    DeployData[] deployedContracts;

    function run() external returns (DeployData[] memory) {
        vm.startBroadcast();

        GachaTeamRegistry gachaTeamRegistry = GachaTeamRegistry(vm.envAddress("GACHA_TEAM_REGISTRY"));
        string[] memory cpuPlayers = new string[](1);
        cpuPlayers[0] = "CPU";

        uint256[] memory monIndices = new uint256[](4);
        uint8[] memory facetIds = new uint8[](4);
        monIndices[0] = 14; // Mulong
        monIndices[1] = 12; // Nirvamma
        monIndices[2] = 11; // Ekineki
        monIndices[3] = 1; // Inutia
        for (uint256 i; i < cpuPlayers.length; i++) {
            gachaTeamRegistry.setTeamForUser(vm.envAddress(cpuPlayers[i]), 0, monIndices, facetIds);
        }

        monIndices[0] = 0; // Ghouliath
        monIndices[1] = 5; // Sofabbi
        monIndices[2] = 8; // Volthare
        monIndices[3] = 9; // Aurox
        for (uint256 i; i < cpuPlayers.length; i++) {
            gachaTeamRegistry.setTeamForUser(vm.envAddress(cpuPlayers[i]), 1, monIndices, facetIds);
        }

        monIndices[0] = 2; // Malalien
        monIndices[1] = 6; // Pengym
        monIndices[2] = 10; // Xmon
        monIndices[3] = 13; // Glob
        for (uint256 i; i < cpuPlayers.length; i++) {
            gachaTeamRegistry.setTeamForUser(vm.envAddress(cpuPlayers[i]), 2, monIndices, facetIds);
        }

        address[] memory empty = new address[](0);
        address[] memory cpuAddresses = new address[](cpuPlayers.length);
        for (uint256 i; i < cpuPlayers.length; i++) {
            cpuAddresses[i] = vm.envAddress(cpuPlayers[i]);
        }
        gachaTeamRegistry.setWhitelistedOpponents(cpuAddresses, empty);

        vm.stopBroadcast();

        return deployedContracts;
    }
}
