#!/usr/bin/env python3
"""sol2rs — the Rust target of the extruder transpiler.

Drives the same front-end as the TypeScript target (lexer / parser /
dependency knowledge) and emits a cargo workspace:

    transpiler/rs-output/
      Cargo.toml          (workspace; generated)
      engine/             (generated crate: one .rs per transpiled .sol)
      runtime/            (hand-written crate, synced from transpiler/runtime-rs)
      differential/       (hand-written crate, synced from transpiler/differential-rs)
      ffi/                (hand-written cdylib stub, synced from transpiler/ffi-rs)

Which files are emitted is governed by ``transpiler-config-rust.json``'s
``includeFiles`` allowlist — the Rust backend is being brought up phase by
phase (value layer + pure libs first) and unlisted files would currently
emit code that fails to compile loudly rather than silently mis-simulate.
Type DISCOVERY still parses the whole source tree so signatures, struct
layouts, and constants resolve across the full codebase.

Usage:
    python3 -m transpiler src/ --target rust -o transpiler/rs-output
"""

import json
import shutil
from pathlib import Path
from typing import Dict, List, Optional, Set

from .lexer import Lexer
from .parser import Parser, SourceUnit
from .codegen_rs import RustCodeGenerator, RustSymbols
from .codegen_rs.symbols import _sanitize_module


DEFAULT_RUST_CONFIG = 'transpiler-config-rust.json'

WORKSPACE_CARGO_TOML = """\
# Auto-generated by sol2rs — do not edit manually
[workspace]
resolver = "2"
members = ["engine", "runtime", "differential", "ffi"]

# Solidity 0.8 checked arithmetic relies on native overflow panics in EVERY
# profile. Do not turn this off: release builds would silently wrap where a
# contract call must revert.
[profile.release]
overflow-checks = true

[profile.bench]
overflow-checks = true
"""

ENGINE_CARGO_TOML = """\
# Auto-generated by sol2rs — do not edit manually
[package]
name = "chomp-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
chomp-rt = { path = "../runtime" }
"""

LIB_RS_HEADER = """\
// Auto-generated by sol2rs — do not edit manually
//
// Generated Rust mirror of the Solidity battle engine. Identifier spelling
// tracks the Solidity source exactly (fidelity > lint style), hence the
// blanket allows below.
#![allow(non_snake_case)]
#![allow(non_camel_case_types)]
#![allow(non_upper_case_globals)]
#![allow(unused_imports)]
#![allow(unused_parens)]
#![allow(unused_mut)]
#![allow(unused_variables)]
#![allow(unused_assignments)]
#![allow(unused_comparisons)]
#![allow(dead_code)]
#![allow(unreachable_code)]
#![allow(unreachable_patterns)]
#![allow(special_module_name)]
#![allow(clippy::all)]
"""


class RustTranspilerConfig:
    def __init__(self, include_files: List[str], dyn_interfaces: Set[str]):
        self.include_files = include_files
        self.dyn_interfaces = dyn_interfaces

    @classmethod
    def load(cls, path: Optional[str] = None) -> 'RustTranspilerConfig':
        config_path = Path(path) if path else Path(__file__).parent / DEFAULT_RUST_CONFIG
        if not config_path.exists():
            print(f'Warning: {config_path} not found; nothing will be emitted')
            return cls([], set())
        data = json.loads(config_path.read_text())
        return cls(
            include_files=data.get('includeFiles', []),
            dyn_interfaces=set(data.get('dynInterfaces', [])),
        )


class SolidityToRustTranspiler:
    def __init__(self, source_dir: str, output_dir: str = 'transpiler/rs-output',
                 config_path: Optional[str] = None):
        self.source_dir = Path(source_dir)
        self.output_dir = Path(output_dir)
        self.config = RustTranspilerConfig.load(config_path)
        self._asts: Dict[str, SourceUnit] = {}

    # ------------------------------------------------------------------
    # Front-end
    # ------------------------------------------------------------------

    def _parse_all(self) -> None:
        """Parse the whole tree for symbol discovery (emission is separate)."""
        for sol_file in sorted(self.source_dir.glob('**/*.sol')):
            rel = sol_file.relative_to(self.source_dir).with_suffix('')
            try:
                source = sol_file.read_text()
                ast = Parser(Lexer(source).tokenize()).parse()
                self._asts[str(rel)] = ast
            except Exception as e:  # discovery is best-effort, like the TS target
                print(f'Warning: could not parse {sol_file} for discovery: {e}')

    # ------------------------------------------------------------------
    # Emission
    # ------------------------------------------------------------------

    def run(self) -> bool:
        self._parse_all()
        symbols = RustSymbols.build(self._asts)

        engine_src = self.output_dir / 'engine' / 'src'
        if engine_src.exists():
            shutil.rmtree(engine_src)
        engine_src.mkdir(parents=True, exist_ok=True)

        emitted: List[str] = []
        all_notes: List[tuple] = []
        ok = True
        for include in self.config.include_files:
            rel = str(Path(include).with_suffix(''))
            ast = self._asts.get(rel)
            if ast is None:
                print(f'Error: include file {include} was not parsed')
                ok = False
                continue
            generator = RustCodeGenerator(symbols, self.config.dyn_interfaces, rel)
            code = generator.generate(ast)
            all_notes.extend(generator.notes)

            out_path = engine_src / self._rust_rel_path(rel)
            out_path.parent.mkdir(parents=True, exist_ok=True)
            out_path.write_text(code)
            emitted.append(rel)
            print(f'Written: {out_path}')

        self._write_lib_rs(engine_src, emitted)
        self._write_workspace_files()
        self._sync_crates()

        warnings = [m for s, m in all_notes if s == 'warning']
        infos = [m for s, m in all_notes if s == 'info']
        if warnings:
            print(f'\nsol2rs: {len(warnings)} warning(s):')
            for w in sorted(set(warnings)):
                print(f'  warning: {w}')
        if infos:
            print(f'sol2rs: {len(set(infos))} info note(s) (external-dispatch stubs etc.)')
        return ok

    @staticmethod
    def _rust_rel_path(rel: str) -> Path:
        parts = rel.replace('\\', '/').split('/')
        sanitized = [_sanitize_module(p) for p in parts[:-1]] + [parts[-1]]
        return Path(*sanitized).with_suffix('.rs')

    def _write_lib_rs(self, engine_src: Path, emitted: List[str]) -> None:
        # Build the nested module tree from emitted file paths.
        tree: dict = {}
        for rel in emitted:
            parts = rel.replace('\\', '/').split('/')
            node = tree
            for p in parts[:-1]:
                node = node.setdefault(_sanitize_module(p), {})
            node[parts[-1]] = None

        lines = [LIB_RS_HEADER]

        def emit_tree(node: dict, depth: int) -> None:
            indent = '    ' * depth
            for name in sorted(node.keys()):
                child = node[name]
                if child is None:
                    lines.append(f'{indent}pub mod {name};')
                else:
                    lines.append(f'{indent}pub mod {name} {{')
                    emit_tree(child, depth + 1)
                    lines.append(f'{indent}}}')

        emit_tree(tree, 0)
        lines.append('')
        (engine_src / 'lib.rs').write_text('\n'.join(lines))
        print(f'Written: {engine_src / "lib.rs"}')

    def _write_workspace_files(self) -> None:
        self.output_dir.mkdir(parents=True, exist_ok=True)
        (self.output_dir / 'Cargo.toml').write_text(WORKSPACE_CARGO_TOML)
        (self.output_dir / 'engine' / 'Cargo.toml').write_text(ENGINE_CARGO_TOML)
        gitignore = self.output_dir / '.gitignore'
        gitignore.write_text('target/\nCargo.lock\n')

    def _sync_crates(self) -> None:
        """Mirror the hand-written crates into the workspace.

        transpiler/runtime-rs, differential-rs, ffi-rs are the git-tracked
        sources of truth (rs-output is regenerated, exactly like ts-output's
        runtime/ mirror)."""
        base = Path(__file__).parent
        for src_name, dst_name in (
            ('runtime-rs', 'runtime'),
            ('differential-rs', 'differential'),
            ('ffi-rs', 'ffi'),
        ):
            src = base / src_name
            if not src.is_dir():
                print(f'Warning: {src} missing; workspace member {dst_name} not synced')
                continue
            dst = self.output_dir / dst_name
            if dst.exists():
                shutil.rmtree(dst)
            shutil.copytree(src, dst, ignore=shutil.ignore_patterns('target', 'Cargo.lock'))
            print(f'Synced: {src} -> {dst}')


def run_rust_target(input_path: str, output: str, config_path: Optional[str] = None) -> None:
    source = Path(input_path)
    if not source.is_dir():
        raise SystemExit('--target rust expects a source directory (e.g. src/)')
    transpiler = SolidityToRustTranspiler(str(source), output, config_path)
    ok = transpiler.run()
    if not ok:
        raise SystemExit(1)
