#!/usr/bin/env python3
"""sol2rs — the Rust target of the extruder transpiler.

Drives the same front-end as the TypeScript target (lexer / parser /
dependency knowledge) and emits a cargo workspace:

    transpiler/rs-output/
      Cargo.toml          (workspace; generated)
      engine/             (generated crate: one .rs per transpiled .sol)
      runtime/            (hand-written crate, synced from transpiler/runtime-rs)
      differential/       (hand-written crate, synced from transpiler/differential-rs)
      ffi/                (hand-written cdylib stub, synced from transpiler/ffi-rs)

Which files are emitted is governed by ``transpiler-config-rust.json``'s
``includeFiles`` allowlist — the Rust backend is being brought up phase by
phase (value layer + pure libs first) and unlisted files would currently
emit code that fails to compile loudly rather than silently mis-simulate.
Type DISCOVERY still parses the whole source tree so signatures, struct
layouts, and constants resolve across the full codebase.

Usage:
    python3 -m transpiler src/ --target rust -o transpiler/rs-output
"""

import json
import shutil
from pathlib import Path
from typing import Dict, List, Optional, Set

from .lexer import Lexer
from .parser import Parser, SourceUnit
from .codegen_rs import RustCodeGenerator, RustSymbols
from .codegen_rs.symbols import _sanitize_module


DEFAULT_RUST_CONFIG = 'transpiler-config-rust.json'

WORKSPACE_CARGO_TOML = """\
# Auto-generated by sol2rs — do not edit manually
[workspace]
resolver = "2"
members = ["engine", "runtime", "differential", "ffi", "strategies"]

# Solidity 0.8 checked arithmetic relies on native overflow panics in EVERY
# profile. Do not turn this off: release builds would silently wrap where a
# contract call must revert.
[profile.release]
overflow-checks = true
lto = "thin"
codegen-units = 1

[profile.bench]
overflow-checks = true
"""

ENGINE_CARGO_TOML = """\
# Auto-generated by sol2rs — do not edit manually
[package]
name = "chomp-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
chomp-rt = { path = "../runtime" }
"""

LIB_RS_HEADER = """\
// Auto-generated by sol2rs — do not edit manually
//
// Generated Rust mirror of the Solidity battle engine. Identifier spelling
// tracks the Solidity source exactly (fidelity > lint style), hence the
// blanket allows below.
#![allow(non_snake_case)]
#![allow(non_camel_case_types)]
#![allow(non_upper_case_globals)]
#![allow(unused_imports)]
#![allow(unused_parens)]
#![allow(unused_mut)]
#![allow(unused_variables)]
#![allow(unused_assignments)]
#![allow(unused_comparisons)]
#![allow(dead_code)]
#![allow(unreachable_code)]
#![allow(unreachable_patterns)]
#![allow(unused_labels)]
#![allow(special_module_name)]
#![allow(clippy::all)]
"""


class RustTranspilerConfig:
    def __init__(self, data: dict):
        self.include_files: List[str] = data.get('includeFiles', [])
        self.dyn_interfaces: Set[str] = set(data.get('dynInterfaces', []))  # legacy, unused
        self.stateful_contracts: Set[str] = set(data.get('statefulContracts', []))
        self.interface_aliases: dict = data.get('interfaceAliases', {})
        self.external_interfaces: Set[str] = set(data.get('externalInterfaces', []))
        self.stub_calls: Set[str] = set(data.get('stubCalls', []))
        self.stub_functions: Set[str] = set(data.get('stubFunctions', []))
        self.noop_calls: Set[str] = set(data.get('noopCalls', []))
        self.skip_bases: Set[str] = set(data.get('skipBases', []))
        self.dispatch_interfaces: Set[str] = set(data.get('dispatchInterfaces', []))
        # Methods NOT on any dispatch interface that callers probe duck-typed
        # (TS: `typeof move.basePower === 'function'`). Each gets an
        # Option-returning `try_<method>` dispatcher over the contracts that
        # actually define it (None = target lacks the method).
        self.duck_dispatch_methods: List[str] = list(data.get('duckDispatchMethods', []))
        self.flatten: dict = data.get('flatten', {})

    @classmethod
    def load(cls, path: Optional[str] = None) -> 'RustTranspilerConfig':
        config_path = Path(path) if path else Path(__file__).parent / DEFAULT_RUST_CONFIG
        if not config_path.exists():
            print(f'Warning: {config_path} not found; nothing will be emitted')
            return cls({})
        return cls(json.loads(config_path.read_text()))


class SolidityToRustTranspiler:
    def __init__(self, source_dir: str, output_dir: str = 'transpiler/rs-output',
                 config_path: Optional[str] = None):
        self.source_dir = Path(source_dir)
        self.output_dir = Path(output_dir)
        self.config = RustTranspilerConfig.load(config_path)
        self._asts: Dict[str, SourceUnit] = {}

    # ------------------------------------------------------------------
    # Front-end
    # ------------------------------------------------------------------

    def _parse_all(self) -> None:
        """Parse the whole tree for symbol discovery (emission is separate)."""
        for sol_file in sorted(self.source_dir.glob('**/*.sol')):
            rel = sol_file.relative_to(self.source_dir).with_suffix('')
            try:
                source = sol_file.read_text()
                ast = Parser(Lexer(source).tokenize()).parse()
                self._asts[str(rel)] = ast
            except Exception as e:  # discovery is best-effort, like the TS target
                print(f'Warning: could not parse {sol_file} for discovery: {e}')

    # ------------------------------------------------------------------
    # Emission
    # ------------------------------------------------------------------

    def _expand_includes(self) -> List[str]:
        """includeFiles entries may be globs (`mons/**/*.sol`) — a new mon
        directory is picked up with zero config changes, like the TS target."""
        out: List[str] = []
        seen = set()
        for include in self.config.include_files:
            if any(ch in include for ch in '*?['):
                matches = sorted(self.source_dir.glob(include))
                if not matches:
                    print(f'Warning: includeFiles glob {include!r} matched nothing')
                for m in matches:
                    rel = str(m.relative_to(self.source_dir))
                    if rel not in seen:
                        seen.add(rel)
                        out.append(rel)
            elif include not in seen:
                seen.add(include)
                out.append(include)
        return out

    def run(self) -> bool:
        self._parse_all()
        symbols = RustSymbols.build(self._asts)
        include_files = self._expand_includes()

        # World configuration: which containers are emitted (files in the
        # allowlist), aliases, harness-external interfaces, flattening.
        included_containers = set()
        for include in include_files:
            rel = str(Path(include).with_suffix(''))
            ast = self._asts.get(rel)
            if ast is not None:
                for c in ast.contracts:
                    included_containers.add(c.name)
        symbols.configure_world(
            self.config.stateful_contracts,
            self.config.interface_aliases,
            self.config.external_interfaces,
            stub_calls=self.config.stub_calls,
            flatten=self.config.flatten,
            included_containers=included_containers,
            stub_functions=self.config.stub_functions,
            noop_calls=self.config.noop_calls,
            dispatch_interfaces=self.config.dispatch_interfaces,
            skip_bases=self.config.skip_bases,
        )
        symbols.compute_needs_world()
        self._symbols = symbols

        engine_src = self.output_dir / 'engine' / 'src'
        if engine_src.exists():
            shutil.rmtree(engine_src)
        engine_src.mkdir(parents=True, exist_ok=True)

        emitted: List[str] = []
        all_notes: List[tuple] = []
        ok = True
        for include in include_files:
            rel = str(Path(include).with_suffix(''))
            ast = self._asts.get(rel)
            if ast is None:
                print(f'Error: include file {include} was not parsed')
                ok = False
                continue
            generator = RustCodeGenerator(symbols, self.config.dyn_interfaces, rel)
            code = generator.generate(ast)
            all_notes.extend(generator.notes)

            out_path = engine_src / self._rust_rel_path(rel)
            out_path.parent.mkdir(parents=True, exist_ok=True)
            out_path.write_text(code)
            emitted.append(rel)
            print(f'Written: {out_path}')

        self._write_world_rs(engine_src, symbols)
        self._write_dispatch_rs(engine_src, symbols)
        self._write_lib_rs(engine_src, emitted)
        self._write_workspace_files()
        self._sync_crates()

        warnings = [m for s, m in all_notes if s == 'warning']
        infos = [m for s, m in all_notes if s == 'info']
        if warnings:
            print(f'\nsol2rs: {len(warnings)} warning(s):')
            for w in sorted(set(warnings)):
                print(f'  warning: {w}')
        if infos:
            print(f'sol2rs: {len(set(infos))} info note(s) (external-dispatch stubs etc.)')
        return ok

    @staticmethod
    def _rust_rel_path(rel: str) -> Path:
        parts = rel.replace('\\', '/').split('/')
        sanitized = [_sanitize_module(p) for p in parts[:-1]] + [parts[-1]]
        return Path(*sanitized).with_suffix('.rs')

    def _write_world_rs(self, engine_src: Path, symbols) -> None:
        """Generated World: Env + contract states + ExternalCalls trait +
        transient reset + the MonState clear helper the Yul port uses."""
        from .codegen_rs.rust_types import RustTypeConverter, rust_ident
        from .codegen_rs.context import RustCodeGenerationContext
        from .codegen_rs.soltypes import TypeInferencer

        ctx = RustCodeGenerationContext(current_file_path='world')
        types = RustTypeConverter(symbols, ctx)
        infer = TypeInferencer(symbols, ctx)

        stateful = symbols.world_state_contracts()

        lines = [
            '// Auto-generated by sol2rs — the World model (see PHASE2-DESIGN.md)',
            'use chomp_rt as rt;',
            'use chomp_rt::{U256, I256, B256, Address};',
            'use crate::Structs::*;',
            'use crate::Enums::*;',
            '',
            '#[derive(Clone, Debug)]',
            'pub struct Env {',
            '    pub msg_sender: Address,',
            '    pub tx_origin: Address,',
            '    pub current_contract: Address,',
            '    pub block_timestamp: U256,',
            '    pub block_number: U256,',
            '}',
            '',
            'impl Default for Env {',
            '    fn default() -> Self {',
            '        Self { msg_sender: Address::ZERO, tx_origin: Address::ZERO,',
            '               current_contract: Address::ZERO,',
            '               block_timestamp: U256::ZERO, block_number: U256::ZERO }',
            '    }',
            '}',
            '',
        ]

        # ExternalCalls trait from accumulated call sites
        lines.append('/// Harness-provided contracts (team registry, matchmaker mocks).')
        lines.append('/// `Send` so FFI battle sessions can live in a handle registry.')
        lines.append('pub trait ExternalCalls: Send {')
        for (iface, method), sig in sorted(symbols.ext_calls.items()):
            if sig is None:
                lines.append(f'    // unresolved: {iface}.{method}')
                continue
            params = ['&mut self', 'target: Address']
            for pname, ptype in zip(sig.param_names, sig.param_types):
                params.append(f'{rust_ident(pname)}: {types.rust_type(ptype)}')
            rets = [types.rust_type(t) for t in sig.return_types]
            ret = '' if not rets else (
                f' -> {rets[0]}' if len(rets) == 1 else f' -> ({", ".join(rets)})'
            )
            lines.append(f'    fn {rust_ident(iface)}_{rust_ident(method)}({", ".join(params)}){ret};')
        lines.append('}')
        lines.append('')
        lines.append('/// Default that panics loudly on any external call.')
        lines.append('pub struct NoExternalCalls;')
        lines.append('impl ExternalCalls for NoExternalCalls {')
        for (iface, method), sig in sorted(symbols.ext_calls.items()):
            if sig is None:
                continue
            params = ['&mut self', '_target: Address']
            for pname, ptype in zip(sig.param_names, sig.param_types):
                params.append(f'_{rust_ident(pname).lstrip("_")}: {types.rust_type(ptype)}')
            rets = [types.rust_type(t) for t in sig.return_types]
            ret = '' if not rets else (
                f' -> {rets[0]}' if len(rets) == 1 else f' -> ({", ".join(rets)})'
            )
            lines.append(f'    fn {rust_ident(iface)}_{rust_ident(method)}({", ".join(params)}){ret} {{')
            lines.append(f'        unimplemented!("ExternalCalls::{iface}_{method}: no harness wired")')
            lines.append('    }')
        lines.append('}')
        lines.append('')

        dispatchables = symbols.dispatchable_contracts()
        lines.append('/// Every deployable transpiled contract; dispatch matches the')
        lines.append('/// target address (registered by deploy_all) to its module.')
        lines.append('#[derive(Clone, Copy, Debug, PartialEq, Eq, Default)]')
        lines.append('pub enum ContractId {')
        lines.append('    #[default]')
        lines.append('    Unknown,')
        for c in dispatchables:
            lines.append(f'    {rust_ident(c)},')
        lines.append('}')
        lines.append('')

        lines.append('pub struct World {')
        lines.append('    pub env: Env,')
        lines.append('    pub ext: Box<dyn ExternalCalls>,')
        lines.append('    pub contract_ids: rt::Mapping<Address, ContractId>,')
        for c in stateful:
            mod_path = '::'.join(symbols.module_of.get(c, (c,)))
            lines.append(f'    pub {rust_ident(c)}: crate::{mod_path}::{rust_ident(c)}State,')
        lines.append('}')
        lines.append('')
        lines.append('impl World {')
        lines.append('    pub fn new(ext: Box<dyn ExternalCalls>) -> Self {')
        lines.append('        Self {')
        lines.append('            env: Env::default(),')
        lines.append('            ext,')
        lines.append('            contract_ids: rt::Mapping::new(),')
        for c in stateful:
            mod_path = '::'.join(symbols.module_of.get(c, (c,)))
            lines.append(f'            {rust_ident(c)}: crate::{mod_path}::{rust_ident(c)}State::default(),')
        lines.append('        }')
        lines.append('    }')
        lines.append('')
        lines.append('    /// Transaction boundary: clear every `transient` state var')
        lines.append('    /// (EIP-1153 auto-clear; the TS proxy does the same).')
        lines.append('    pub fn reset_transient(&mut self) {')
        for c in stateful:
            cdef = symbols.contract_defs.get(c)
            parts = [cdef] + [
                symbols.contract_defs.get(b)
                for b in symbols.flatten_bases.get(c, [])
                if symbols.contract_defs.get(b) is not None
            ]
            for part in parts:
                for var in part.state_variables:
                    if var.mutability == 'transient':
                        t = infer.from_type_name(var.type_name)
                        lines.append(
                            f'        self.{rust_ident(c)}.{rust_ident(var.name)} = '
                            f'{types.default_value(t)};'
                        )
        lines.append('    }')
        lines.append('}')
        lines.append('')
        lines.append('/// HRTB funnel: pins a selector closure (see selector-lowered')
        lines.append('/// storage params) to `for<\'w> Fn(&\'w mut World) -> &\'w mut T`,')
        lines.append('/// which plain closure inference cannot reach on its own.')
        lines.append('pub fn sel<T, F: for<\'w> Fn(&\'w mut World) -> &\'w mut T>(f: F) -> F {')
        lines.append('    f')
        lines.append('}')
        lines.append('')
        lines.append('/// MonState with every delta at the cleared sentinel (the Yul')
        lines.append('/// slot-clear writes PACKED_CLEARED_MON_STATE; this is that state).')
        lines.append('pub fn cleared_mon_state() -> crate::Structs::MonState {')
        lines.append('    crate::Structs::MonState {')
        for f in ('hpDelta', 'staminaDelta', 'speedDelta', 'attackDelta',
                  'defenceDelta', 'specialAttackDelta', 'specialDefenceDelta'):
            lines.append(f'        {f}: crate::Constants::CLEARED_MON_STATE_SENTINEL,')
        lines.append('        isKnockedOut: false,')
        lines.append('        shouldSkipTurn: false,')
        lines.append('    }')
        lines.append('}')
        lines.append('')

        lines.extend(self._deploy_all_lines(symbols))

        (engine_src / 'world.rs').write_text('\n'.join(lines))
        print(f'Written: {engine_src / "world.rs"}')

    def _deploy_all_lines(self, symbols) -> List[str]:
        """`deploy_all(world, addr_of)`: registers every dispatchable's
        ContractId under its harness-supplied address and constructs the
        stateful ones, resolving interface-typed constructor args to dep
        ADDRESSES with the same DependencyResolver the TS factories use —
        the two backends wire identically by construction."""
        from .codegen_rs.rust_types import rust_ident
        from .dependency_resolver.resolver import DependencyResolver

        dispatchables = symbols.dispatchable_contracts()
        stateful = set(symbols.world_state_contracts())
        resolver = DependencyResolver(
            overrides_path=str(Path(__file__).parent / 'transpiler-config.json'),
            known_classes=set(dispatchables),
        )
        resolver.add_aliases(self.config.interface_aliases)

        out = [
            '/// Register + construct every transpiled contract. `addr_of` is the',
            '/// harness address book (the lockstep gate feeds the TS-exported one;',
            '/// the arena assigns its own).',
            'pub fn deploy_all(world: &mut World, addr_of: &dyn Fn(&str) -> Address) {',
        ]
        for c in dispatchables:
            out.append(f'    world.contract_ids.set(addr_of("{c}"), ContractId::{rust_ident(c)});')
        out.append('')
        for c in dispatchables:
            if c not in stateful:
                continue
            cdef = symbols.contract_defs.get(c)
            ctor = cdef.constructor if cdef is not None else None
            mod_path = '::'.join(symbols.module_of.get(c, (c,)))
            if ctor is None:
                continue  # default state is already in place
            args = []
            unsupported = None
            params = [(p.name or f'_arg{i}', p.type_name.name if p.type_name else '')
                      for i, p in enumerate(ctor.parameters)]
            resolved = {
                pn: r for pn, _pt, r in resolver.resolve_constructor_params(
                    c, params,
                    known_interfaces=set(symbols.interfaces),
                    known_contracts=set(symbols.contracts),
                )
            }
            for pname, ptype in params:
                r = resolved.get(pname)
                if r is None:
                    unsupported = f'non-contract ctor param {pname}: {ptype}'
                    break
                if getattr(r, 'is_array', False):
                    unsupported = f'array ctor param {pname}'
                    break
                impl = getattr(r, 'resolved_as', None)
                if impl in (None, '@self'):
                    args.append('Address::ZERO')
                else:
                    args.append(f'addr_of("{impl}")')
            if unsupported is not None:
                out.append(f'    // {c}: constructed by the harness ({unsupported})')
                continue
            if symbols.constructor_needs_world(c):
                args = ['world'] + args
            out.append(f'    let __s = crate::{mod_path}::construct({", ".join(args)});')
            out.append(f'    world.{rust_ident(c)} = __s;')
        out.append('}')
        out.append('')
        return out

    def _write_dispatch_rs(self, engine_src: Path, symbols) -> None:
        """Generated dispatch tables: one fn per dispatch-interface method,
        matching the target address's ContractId to the implementor's
        module (with the msg.sender frame push around the call)."""
        from .codegen_rs.rust_types import RustTypeConverter, rust_ident
        from .codegen_rs.context import RustCodeGenerationContext

        ctx = RustCodeGenerationContext(current_file_path='dispatch')
        types = RustTypeConverter(symbols, ctx)

        dispatchables = symbols.dispatchable_contracts()
        lines = [
            '// Auto-generated by sol2rs — address-based interface dispatch',
            '// (see PHASE3-DESIGN.md). deploy_all registers ContractIds.',
            'use chomp_rt as rt;',
            'use chomp_rt::{U256, I256, B256, Address};',
            'use crate::world::{World, ContractId};',
            '#[allow(unused_imports)] use crate::Structs::*;',
            '#[allow(unused_imports)] use crate::Enums::*;',
            '',
        ]
        for iface in sorted(getattr(symbols, 'dispatch_interfaces', set())):
            impls = [c for c in dispatchables if symbols.implements(c, iface)]
            methods = sorted(
                {key[1] for key in symbols.functions if key[0] == iface}
            )
            for method in methods:
                sig = symbols.lookup_function(iface, method)
                if sig is None:
                    continue
                params = ['world: &mut World', 'target: Address']
                arg_names = []
                for pname, ptype in zip(sig.param_names, sig.param_types):
                    n = rust_ident(pname) if pname else f'_arg{len(arg_names)}'
                    rt_t = types.rust_type(ptype)
                    if ptype.is_memory_ref or ptype.kind == 'mapping':
                        params.append(f'{n}: &mut {rt_t}')
                    else:
                        params.append(f'{n}: {rt_t}')
                    arg_names.append(n)
                rets = [types.rust_type(t) for t in sig.return_types]
                ret = '' if not rets else (
                    f' -> {rets[0]}' if len(rets) == 1 else f' -> ({", ".join(rets)})'
                )
                lines.append(f'pub fn {iface}_{method}({", ".join(params)}){ret} {{')
                lines.append('    let __id = world.contract_ids.get(&target);')
                lines.append('    let __saved_sender = world.env.msg_sender;')
                lines.append('    let __saved_contract = world.env.current_contract;')
                lines.append('    world.env.msg_sender = world.env.current_contract;')
                lines.append('    world.env.current_contract = target;')
                lines.append('    let __r = match __id {')
                for c in impls:
                    impl_sig = symbols.lookup_function(c, method)
                    if impl_sig is None:
                        lines.append(
                            f'        ContractId::{rust_ident(c)} => '
                            f'panic!("{c} lacks {iface}.{method}"),'
                        )
                        continue
                    mod_path = '::'.join(symbols.module_of.get(c, (c,)))
                    call_args = (['world'] if impl_sig.needs_world else []) + arg_names
                    lines.append(
                        f'        ContractId::{rust_ident(c)} => '
                        f'crate::{mod_path}::{rust_ident(method)}({", ".join(call_args)}),'
                    )
                lines.append(
                    f'        __other => panic!("{iface}.{method}: no dispatch for '
                    f'{{:?}} at {{:?}}", __other, target),'
                )
                lines.append('    };')
                lines.append('    world.env.msg_sender = __saved_sender;')
                lines.append('    world.env.current_contract = __saved_contract;')
                lines.append('    __r')
                lines.append('}')
                lines.append('')

        # Duck-typed optional dispatch (duckDispatchMethods): strategy code
        # probes methods that are NOT on any IMoveSet-style interface (TS:
        # `typeof move.basePower === 'function'` in heuristic-shared /
        # heuristic-native). Emit `try_<method>` returning Option — Some for
        # contracts that define it, None otherwise (no panic arm).
        for method in sorted(self.config.duck_dispatch_methods):
            impls = [
                (c, symbols.lookup_function(c, method))
                for c in dispatchables
            ]
            impls = [(c, s) for c, s in impls if s is not None]
            if not impls:
                continue
            sig = impls[0][1]
            params = ['world: &mut World', 'target: Address']
            arg_names = []
            for pname, ptype in zip(sig.param_names, sig.param_types):
                n = rust_ident(pname) if pname else f'_arg{len(arg_names)}'
                params.append(f'{n}: {types.rust_type(ptype)}')
                arg_names.append(n)
            rets = [types.rust_type(t) for t in sig.return_types]
            ret = rets[0] if len(rets) == 1 else f'({", ".join(rets)})'
            lines.append(f'pub fn try_{method}({", ".join(params)}) -> Option<{ret}> {{')
            lines.append('    let __id = world.contract_ids.get(&target);')
            lines.append('    let __saved_sender = world.env.msg_sender;')
            lines.append('    let __saved_contract = world.env.current_contract;')
            lines.append('    world.env.msg_sender = world.env.current_contract;')
            lines.append('    world.env.current_contract = target;')
            lines.append('    let __r = match __id {')
            for c, impl_sig in impls:
                mod_path = '::'.join(symbols.module_of.get(c, (c,)))
                call_args = (['world'] if impl_sig.needs_world else []) + arg_names
                lines.append(
                    f'        ContractId::{rust_ident(c)} => '
                    f'Some(crate::{mod_path}::{rust_ident(method)}({", ".join(call_args)})),'
                )
            lines.append('        _ => None,')
            lines.append('    };')
            lines.append('    world.env.msg_sender = __saved_sender;')
            lines.append('    world.env.current_contract = __saved_contract;')
            lines.append('    __r')
            lines.append('}')
            lines.append('')

        (engine_src / 'dispatch.rs').write_text('\n'.join(lines))
        print(f'Written: {engine_src / "dispatch.rs"}')

    def _write_lib_rs(self, engine_src: Path, emitted: List[str]) -> None:
        # Build the nested module tree from emitted file paths.
        tree: dict = {}
        for rel in emitted:
            parts = rel.replace('\\', '/').split('/')
            node = tree
            for p in parts[:-1]:
                node = node.setdefault(_sanitize_module(p), {})
            node[parts[-1]] = None

        lines = [LIB_RS_HEADER]

        def emit_tree(node: dict, depth: int) -> None:
            indent = '    ' * depth
            for name in sorted(node.keys()):
                child = node[name]
                if child is None:
                    lines.append(f'{indent}pub mod {name};')
                else:
                    lines.append(f'{indent}pub mod {name} {{')
                    emit_tree(child, depth + 1)
                    lines.append(f'{indent}}}')

        emit_tree(tree, 0)
        lines.append('pub mod world;')
        lines.append('pub mod dispatch;')
        lines.append('')
        (engine_src / 'lib.rs').write_text('\n'.join(lines))
        print(f'Written: {engine_src / "lib.rs"}')

    def _write_workspace_files(self) -> None:
        self.output_dir.mkdir(parents=True, exist_ok=True)
        (self.output_dir / 'Cargo.toml').write_text(WORKSPACE_CARGO_TOML)
        (self.output_dir / 'engine' / 'Cargo.toml').write_text(ENGINE_CARGO_TOML)
        gitignore = self.output_dir / '.gitignore'
        gitignore.write_text('target/\nCargo.lock\n')

    def _sync_crates(self) -> None:
        """Mirror the hand-written crates into the workspace.

        transpiler/runtime-rs, differential-rs, ffi-rs are the git-tracked
        sources of truth (rs-output is regenerated, exactly like ts-output's
        runtime/ mirror)."""
        base = Path(__file__).parent
        for src_name, dst_name in (
            ('runtime-rs', 'runtime'),
            ('differential-rs', 'differential'),
            ('ffi-rs', 'ffi'),
            ('strategies-rs', 'strategies'),
        ):
            src = base / src_name
            if not src.is_dir():
                print(f'Warning: {src} missing; workspace member {dst_name} not synced')
                continue
            dst = self.output_dir / dst_name
            if dst.exists():
                shutil.rmtree(dst)
            shutil.copytree(src, dst, ignore=shutil.ignore_patterns('target', 'Cargo.lock'))
            print(f'Synced: {src} -> {dst}')


def run_rust_target(input_path: str, output: str, config_path: Optional[str] = None) -> None:
    source = Path(input_path)
    if not source.is_dir():
        raise SystemExit('--target rust expects a source directory (e.g. src/)')
    transpiler = SolidityToRustTranspiler(str(source), output, config_path)
    ok = transpiler.run()
    if not ok:
        raise SystemExit(1)
